### ISSUE TITLE
If you create "state" rules for IP v6, then you cannot create them for IP v4.

### ISSUE THREAD

**Issue by plwhite** [ldx/python-iptables#112]
I just spent a few hours figuring out how to filter on state using python-iptables when there are both IPv6 and IPv4 rules. Since this was painful, it seems worth raising as an issue in case anybody hits the same problem, perhaps so a warning can go in the docs.

Some trivial sample code below showing the problem. The underlying issue seems to be that, although I can use state matching for either IPv4 or IPv6, I cannot do both in the same program. The resolution was to use match type "conntrack" and "ctstate" for the IPv6 rules (only) (i.e. `rule.create_match("conntrack")` followed by `match.ctstate=["INVALID"]`).

```
import iptc

# Change this value from True to False to make the failure go away
name = "plw"

# Create both IP v4 and IP v6 chains, both empty
table = iptc.Table6(iptc.Table6.FILTER)
if not table.is_chain(name):
    chain = table.create_chain(name)
else:
    chain = iptc.Chain(table,name)
chain.flush()

table = iptc.Table(iptc.Table.FILTER)
if not table.is_chain(name):
    chain = table.create_chain(name)
else:
    chain = iptc.Chain(table,name)
chain.flush()

# Add a rule to both.
table = iptc.Table6(iptc.Table6.FILTER)
chain = iptc.Chain(table,name)
rule  = iptc.Rule6()
rule.create_target("DROP")
match = rule.create_match("state")
match.state = ["INVALID"]
# It turned out not to matter if I inserted the rule or not
#chain.insert_rule(rule,0)

table = iptc.Table(iptc.Table.FILTER)
chain = iptc.Chain(table,name)
rule  = iptc.Rule()
rule.create_target("DROP")
match = rule.create_match("state")
match.state = "INVALID"
#chain.insert_rule(rule,0)
```

**Comment by ApoXalvation** [comment]
Hello, It looks like this issue still occurs for external kernel modules like jool/jool_siit
`>>> import iptc
>>> iptc.Rule6().create_target("JOOL_SIIT")
<iptc.ip4tc.Target object at 0x7f106a25ab80>
>>> iptc.Rule().create_target("JOOL_SIIT")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/share/virtualenvs/qualia-gdQNZkWv/lib/python3.8/site-packages/iptc/ip4tc.py", line 1002, in create_target
    target = Target(self, name=name, revision=revision, goto=goto)
  File "/root/.local/share/virtualenvs/qualia-gdQNZkWv/lib/python3.8/site-packages/iptc/ip4tc.py", line 728, in __init__
    raise XTablesError("can't find target %s" % (name))
iptc.errors.XTablesError: can't find target JOOL_SIIT`

**Comment by ldx** [comment]
@ApoXalvation I tried to reproduce it after installing Jool from the deb packages, but the process gets stuck in kernel, and only reboot helps:

     8607 pts/10   S+     0:00  |   \_ sudo /home/vilmos/.virtualenvs/iptc/bin/python issue112.py
     8608 pts/10   D+     0:02  |       \_ /home/vilmos/.virtualenvs/iptc/bin/python issue112.py

Code:

    import iptc
    t6 = iptc.Rule6().create_target("JOOL_SIIT")
    t = iptc.Rule().create_target("JOOL_SIIT")

**Comment by ApoXalvation** [comment]
@ldx After package installation `sudo apt install jool-dkms jool-tools` ensure that You have enabled kernel modules `/sbin/modprobe jool_siit`

**Comment by ldx** [comment]
Thanks, that helped!

This code works for me:

    import iptc
    
    rule6 = iptc.Rule6()
    target6 = rule6.create_target("JOOL_SIIT")
    print(rule6.nfproto, target6.name)
    
    rule = iptc.Rule()
    target = rule.create_target("JOOL_SIIT")
    print(rule.nfproto, target.name)

Output:

    10 JOOL_SIIT
    2 JOOL_SIIT

Using:

    $ iptables --version
    iptables v1.8.2 (nf_tables)

**Comment by ApoXalvation** [comment]
So it might be a problem with iptables version. I'll check this tommorow but this is good news for me.
Thank You for Your time. @ldx

**Comment by ldx** [comment]
No worries, let me know how it goes. Another thing to check is your python-iptables version.

**Comment by ApoXalvation** [comment]
with: python-iptables==1.0.0 and iptables v1.8.4 (nf_tables) I still get the same error...
Which os do You use?

**Comment by ApoXalvation** [comment]
It works fine on centos 8 but not on ubuntu 20.04 (tested with "v1.8.4 (nf_tables)" and  "v1.8.4 (legacy)"

**Comment by ldx** [comment]
I use Debian 10. I also booted up an Ubuntu 20.04 VM, and the same, the sample code above works fine.

**Comment by ApoXalvation** [comment]
@ldx The last attempt with `python-iptables==1.0.0` on centos 8 and honestly this error looks different than previous, but I am trying to achieve the same thing and faced every time different issues on various OSes:
```
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iptc
>>> iptc.easy.add_rule("nat", "PREROUTING", {"protocol": "udp","udp": {"dport": "51821"},"target": {"DNAT": {"to-destination": "10.34.07.2:51821"}}}, 0, False)
>>> iptc.easy.add_rule("mangle", "PREROUTING", {"target": {"JOOL_SIIT": {"instance": "3407"}}}, 0, True)
>>> iptc.easy.add_rule("mangle", "PREROUTING", {"target": {"JOOL_SIIT": {"instance": "3407"}}}, 0, False)
python-iptables: target "JOOL_SIIT" already registered
```

**Comment by ldx** [comment]
@ApoXalvation I tried both Ubuntu 20.04 and CentOS8, same result:

    Python 3.8.3 (default, Aug 31 2020, 16:03:14)
    [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import iptc
    >>> iptc.easy.add_rule("nat", "PREROUTING", {"protocol": "udp","udp": {"dport": "51821"},"target": {"DNAT": {"to-destination": "10.34.07.2:51821"}}}, 0, False)
    >>> iptc.easy.add_rule("mangle", "PREROUTING", {"target": {"JOOL_SIIT": {"instance": "3407"}}}, 0, True)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/root/python-iptables/iptc/easy.py", line 74, in add_rule
        iptc_chain.append_rule(iptc_rule)
      File "/root/python-iptables/iptc/ip4tc.py", line 1476, in append_rule
        raise ValueError("invalid rule")
    ValueError: invalid rule
    >>> iptc.easy.add_rule("mangle", "PREROUTING", {"target": {"JOOL_SIIT": {"instance": "3407"}}}, 0, False)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/root/python-iptables/iptc/easy.py", line 74, in add_rule
        iptc_chain.append_rule(iptc_rule)
      File "/root/python-iptables/iptc/ip4tc.py", line 1476, in append_rule
        raise ValueError("invalid rule")
    ValueError: invalid rule
    >>>

(I guess `invalid rule` is what is expected?)
