### ISSUE TITLE
Segfault when adding an ipset rule

### ISSUE THREAD

**Issue by devicenull** [ldx/python-iptables#123]
I'm seeing segfaults if I try to add an ipset rule where the set doesn't exist.  For example:

	import iptc

	chain = iptc.Chain(iptc.Table(iptc.Table.MANGLE), 'PREROUTING')
	rule = iptc.Rule()
	rule.target = rule.create_target('DROP')
	rule.dst = '1.2.3.4/255.255.255.255'

	match = rule.create_match('set')
	match.match_set = ['doesnt_exist', 'src']

	chain.append_rule(rule)

Once I create the set (ipset create doesnt_exist hash:ip) this code works properly

This was tested on CentOS 6.6 x86_64

**Comment by ldx** [comment]
No response, so closing this. Feel free to reopen if this is still an issue.
