### ISSUE TITLE
How to know which port is being reported when using get_counters?

### ISSUE THREAD

**Issue by caizixian** [ldx/python-iptables#130]
I set iptables rule using `/sbin/iptables -A INPUT -p tcp --dport 80`.
When using rule.get_counters(), I only get a tuple contains TX RX. And when `rule.dst`, I only get `0.0.0.0/0.0.0.0`
How can I know which port is being reported when using get_counters? Using match?

**Comment by ldx** [comment]
Hm, I'm not sure I understand this.

Do you have some example code?

**Comment by caizixian** [comment]
Never mind. I've solved it.
