### ISSUE TITLE
Document which operations are atomic

### ISSUE THREAD

**Issue by nbartos** [ldx/python-iptables#131]
I'm attempting to make a module that will replace a single chain only inside a table atomically.  I've been digging a bit but I cannot figure out which operations are truly atomic.  For example, the command line utility iptables-restore is atomic at the table level.

**Comment by ldx** [comment]
If you want to batch changes, then disable autocommit, and commit manually (iptables-restore does the same). The README has some documentation on how to do this. Let me know if you need help, and I can add some more info to the docs.
