### ISSUE TITLE
Could you please make tag 0.6.0 available on pypi

### ISSUE THREAD

**Issue by plwhite** [ldx/python-iptables#132]
Background to this request is that we need the fix for bug #111, which was fixed in 0.6.0 but not in 0.5.0. The most recent version available is 0.5.0 (https://pypi.python.org/pypi/python-iptables/0.5.0).

While we can manually install as a workaround, we'd like to just install by using `pip`.

Thanks

**Comment by ldx** [comment]
I plan to make a new release sometime this week. Let me know if this is blocking you and I can prioritize it.

**Comment by plwhite** [comment]
Thanks - if this is going to happen within a few days (or even a few weeks) then that would be perfect for us. We currently have some pretty hacky workarounds in place so it isn't hurting us too much in the short term, but I'd like those not to persist for too long.

**Comment by ldx** [comment]
Done.

**Comment by plwhite** [comment]
That's great, thanks.
