### ISSUE TITLE
Target already registered when applying rule for both IPv4 and IPv6

### ISSUE THREAD

**Issue by jta** [ldx/python-iptables#135]
I'm hitting a problem when trying to insert rules to both iptables and ip6tables (v1.4.13). The minimal test script I can muster:

```
import iptc

table = iptc.Table(iptc.Table.RAW)
chain = iptc.Chain(table, "PREROUTING")
rule = iptc.Rule()
rule.create_target("ACCEPT")
chain.insert_rule(rule)
table.commit()

table6 = iptc.Table6(iptc.Table6.RAW)
chain6 = iptc.Chain(table, "PREROUTING")
rule6 = iptc.Rule6()
rule6.create_target("ACCEPT")
chain6.insert_rule(rule6)
table6.commit()
```

Running this gives me the following output:
```
/usr/local/lib/xtables/libxt_standard.so: no "standard" extension found for this protocol
python-iptables: target `standard' already registered.
```

This also seems to happen when trying to find matches.

**Comment by ldx** [comment]
Hey @jta,

is this causing any other unwanted side effects? This is due to python-iptables making sure the extension is registered, but other than this message on stdout, should not cause any issues.

**Comment by jta** [comment]
Interesting, I seem to hit a system exit. Tracing the error message to `iptables/xtables.c:xtables_fully_register_pending_target`:

```
        old = xtables_find_target(me->name, XTF_DURING_LOAD);
        if (old) {
                struct xtables_target **i;

                if (old->revision == me->revision &&
                    old->family == me->family) {
                        fprintf(stderr,
                                "%s: target `%s' already registered.\n",
                                xt_params->program_name, me->name);
                        exit(1);
                }
```

**Comment by ldx** [comment]
I have to install that specific version of iptables to test this. Give me a few days.

**Comment by jta** [comment]
Any luck in chasing this? I might try to upgrade iptables to see if I can replicate with later versions.

**Comment by ldx** [comment]
I could not find a VM with 1.4.13, but tested with 1.4.12. Besides this line on stderr:

    /lib/xtables/libxt_standard.so: no "standard" extension found for this protocol

the script runs until the end.

What version of python-iptables do you use?

**Comment by ldx** [comment]
Interesting thing, as I was working on #138, I bumped into this issue. Python-iptables might need to do some extra work to make sure it's not trying to load an already registered extension.

**Comment by jta** [comment]
Thanks! Will check this out later.
