### ISSUE TITLE
Is there any mailing list for update notification?

### ISSUE THREAD

**Issue by caizixian** [ldx/python-iptables#136]

**Comment by ldx** [comment]
If you have a project on Github that depends on python-iptables, you can use pypi-notifier:

http://www.pypi-notifier.org/

Does this solve your problem?

**Comment by caizixian** [comment]
Yes. Thx!

**Comment by caizixian** [comment]
@ldx Actually I have a project using python-iptables. caizixian/tcpstat

**Comment by ldx** [comment]
Cool, I'm always happy to see python-iptables being used for interesting use cases like this!
