### ISSUE TITLE
Setting --name parameter in match rules

### ISSUE THREAD

**Issue by xadhoom** [ldx/python-iptables#143]
Some match targets in iptables ( http://www.netfilter.org/documentation/HOWTO/netfilter-extensions-HOWTO.html#toc3.16 ) have --name in their parameters.
Unfortunately this cannot be set using match.name because name is protected.

Looking into the Match object __setattr__ method the parse method is used to set the parameters.

Is safe to call match.parse(name,val) to set the parameter "--name" ? 
It works, but I'm wondering if parse is for pubblic use or not. 

Maybe parse can always called to set parameters of the match without passing from __setattr__ ?

**Comment by ldx** [comment]
Yes, in this case you can call `parse()`. It's a bit ugly, but changing `match.name` to `match.match_name` or something similar to avoid colliding with a parameter name in the extension would probably break existing applications/scripts.

**Comment by xadhoom** [comment]
well, maybe is worth adding a new public method like "set_parameter" that is just an alias for parse that can be used instead of just passing from __setattr__ ? just to be more clear :)

**Comment by ldx** [comment]
Good idea! Would you like to submit a pull request with this change?

**Comment by xadhoom** [comment]
Created, hope is correct for you. Closing this one.
