### ISSUE TITLE
SIGSEGV for this module

### ISSUE THREAD

**Issue by anan-lee** [ldx/python-iptables#145]
when i run below code:

rule = iptc.Rule()

set = iptc.Match(rule, 'set')
set.match_set = ['test', 'ddst,dst']

it closed with segmentation fault. ( i knew the 'ddst' is not exist. )

the question:
    how can i catch and handle this signal or let the program to  run gracefully?

**Comment by ldx** [comment]
Can you tell me
- the version of python-iptables,
- the version of iptables and
- the linux distribution and its version you use?

A segfault should not happen no matter what you do with python-iptables.

Thanks!

**Comment by anan-lee** [comment]
OK,  thanks for your feedback.
iptc module has been installed by pip and the version is "0.7.0" .
my operation system is CentOS release 6.3 (Final).
the version if iptables is v1.4.7.

And there was any other information you needed?

**Comment by ldx** [comment]
@anan-lee this is now fixed in latest master. It will be included in the next release too.

Thanks for reporting this!
