### ISSUE TITLE
XTablesError: can't find match

### ISSUE THREAD

**Issue by jta** [ldx/python-iptables#150]
In release `0.8.0` I'm running into errors when trying to configure a table:

```
  File "/usr/local/lib/python2.7/dist-packages/<snipped>", line 259, in icmpfrag
    rule.create_match("icmp6").icmpv6_type = "2/0"
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 935, in create_match
    match = Match(self, name=name, revision=revision)
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 535, in __init__
    raise XTablesError("can't find match %s" % (name))
```
This exception is only raised the second time a try to configure the table from within a process that does both IPv4 and IPv6 configuration. I've managed to reduce the offending code to the following return statement, which was indeed an addition between `0.7.0` to `0.8.0`:

https://github.com/ldx/python-iptables/blob/master/iptc/xtables.py#L905

I haven't had much time to look into why iptc thinks the match is registered (which it should be the second time round). Any pointers would be greatly appreciated.

**Comment by ldx** [comment]
Hey,

can you show me a script that reproduces this?

Thanks!

**Comment by jta** [comment]
Sorry, took me a while to break down a reasonable example to replicate. Here goes:

https://gist.github.com/jta/7d7e51e6c4cf0b355232

This script just reconfigures `mangle` `POSTROUTING` and adds two rules: one manipulating TTL and another DSCP. It does this for both IPv4 and IPv6.

The first time round everything goes fine, the second time round when create the `TTL` target I get the error, in this case:

```
Traceback (most recent call last):
  File "test.py", line 59, in <module>
    Iptables.reconfigure()
  File "test.py", line 30, in reconfigure
    rules = [cls.get_ttl_rule(), cls.get_dscp_rule()]
  File "test.py", line 12, in get_ttl_rule
    rule.create_target("TTL").ttl_set = str(2)
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 942, in create_target
    target = Target(self, name=name, revision=revision)
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 683, in __init__
    raise XTablesError("can't find target %s" % (name))
iptc.xtables.XTablesError: can't find target TTL
```
Hope that helps.

**Comment by ldx** [comment]
Hi @jta, the branch `issue150` fixes this issue.

Can you confirm that your script works now on your end?

**Comment by jta** [comment]
Works great, thanks!

**Comment by ldx** [comment]
Happy to hear! This will be part of the next release.
