### ISSUE TITLE
Problem with recent Module

### ISSUE THREAD

**Issue by Azidburn** [ldx/python-iptables#158]
Hi,

i will use recent match in my Code.
I alway get "AttributeError: can't set attribute".

Here is an example Code
```
import iptc

table = iptc.Table(iptc.Table.FILTER)
targetchain = iptc.Chain(table, 'FORWARD')
rule = iptc.Rule()
match = rule.create_match('recent')
match.set_parameter('set')
match.set_parameter('name', 'testlist')
targetchain.insert_rule(rule,1)
```

I think the issue is that the recent module have a parameter called "name". I can't set any value to this parameter.

My version are
python: 2.7.9
iptables: 1.4.21
iptc: 0.9.0

**Comment by ldx** [comment]
@Azidburn fixed in latest master, thanks for reporting this.
