### ISSUE TITLE
Problem with Dualstack Rules and Geoip Match

### ISSUE THREAD

**Issue by Azidburn** [ldx/python-iptables#164]
Hey,

i try to add a geoip rule for iptables and ip6tables. The issue always happens on the second rule.
The order IPv4, IPv6 or IPv6, IPv4 makes no difference. Adding only IPv4 or IPv6 in a run works.

Here a demo code
```
import iptc
#ipv4 Rule
table = iptc.Table(iptc.Table.FILTER)
chain = iptc.Chain(table, 'FORWARD')
rule = iptc.Rule()
match = rule.create_match('geoip');
match.set_parameter('src-cc', 'US')
rule.target = rule.create_target('DROP')
chain.append_rule(rule)

#ipv6 Rule
table = iptc.Table6(iptc.Table.FILTER)
chain = iptc.Chain(table, 'FORWARD')
rule = iptc.Rule6()
rule.target = rule.create_target('DROP')
match = rule.create_match('geoip');
match.set_parameter('src-cc', 'US')
rule.target = rule.create_target('DROP')
chain.append_rule(rule)
```

My version are
```
iptables:  v1.4.21
python-iptables: 0.9.0
Linux Kernel: 4.1.3
```
I tried to add the rules manual with iptables and ip6tables. Both works without problems.

thanks 
Marc

**Comment by ldx** [comment]
I don't have a geoip match installed with iptables on my laptop, but changing the match to another extension, this works with latest master from git.

**Comment by Azidburn** [comment]
The geoip match is from xtables-extensions. I tried the latest master from git, but no changes.

Here the Stacktrace:

```
Traceback (most recent call last):
  File "geoip_prop.py", line 16, in <module>
    match = rule.create_match('geoip');
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 959, in create_match
    match = Match(self, name=name, revision=revision)
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 543, in __init__
    raise XTablesError("can't find match %s" % (name))
iptc.xtables.XTablesError: can't find match geoip
```

**Comment by ldx** [comment]
Installed geoip and managed to reproduce the problem.

Unfortunately, this is due to the fact that the geoip extension is out of tree and has a different init function than the built-in iptables extensions. Python-iptables can't initalize it for the second protocol since the init function is static.

The only way I see to make this work is to patch this in `extensions/libxt_geoip.c`. Let me know if you'd like to do it.

**Comment by ldx** [comment]
@Azidburn here's what you need to change in `extensions/libxt_geoip.c` so it'll work with python-iptables:

    diff -ruN extensions-orig/libxt_geoip.c extensions/libxt_geoip.c
    --- extensions-orig/libxt_geoip.c       2015-11-21 09:14:11.769756784 -0800
    +++ extensions/libxt_geoip.c    2015-11-21 09:12:41.037627285 -0800
    @@ -308,7 +308,7 @@
            },
     };
    
    -static __attribute__((constructor)) void geoip_mt_ldr(void)
    +__attribute__((constructor)) void libxt_geoip_init(void)
     {
            xtables_register_matches(geoip_match,
                    sizeof(geoip_match) / sizeof(*geoip_match));
