### ISSUE TITLE
Compare rules

### ISSUE THREAD

**Issue by l-flame** [ldx/python-iptables#166]
I don't quite sure, if it's the right place to ask, but how can one compare one rule instance with other?

I want to do something like this:
```python
def get_def_rule():
    rule = iptc.Rule()
    rule.in_interface = "eth0"
    rule.src = "192.168.1.0/255.255.255.0"
    rule.protocol = "tcp"
    return rule

table = iptc.Table(tablename)
chain = iptc.Chain(table, chain)
for rule in chain.rules:
    if rule == get_def_rule():
        print 'Matched'
```

**Comment by ldx** [comment]
@l-flame this will work if you add a target. Without a target, your rule is not complete.

    #!/usr/bin/env python
    
    import iptc
    
    def get_def_rule():
        rule = iptc.Rule()
        rule.in_interface = "eth0"
        rule.src = "192.168.1.0/255.255.255.0"
        rule.protocol = "tcp"
        rule.create_target("ACCEPT")
        return rule
    
    table = iptc.Table('filter')
    chain = iptc.Chain(table, 'INPUT')
    for rule in chain.rules:
        if rule == get_def_rule():
            print 'Matched'

HTH

**Comment by l-flame** [comment]
Thank you. 

I search in the docs, but didn't found it. Sorry.

**Comment by ldx** [comment]
No worries! Happy this helped.
