### ISSUE TITLE
Accessing Network Namespaces

### ISSUE THREAD

**Issue by RaginBajin** [ldx/python-iptables#169]
Has anyone done anything using python-iptables within a network namespace?  A quick example would be great.

**Comment by ldx** [comment]
Hey @RaginBajin, can you give me an example how that works via the command line? Or do you mean changing iptables rules in a container while your Python application using python-iptables runs on the host (i.e. you want to step into the container namespace)?

**Comment by RaginBajin** [comment]
Sure @ldx 

Here's an example command that I would run:

ip netns exec qrouter-XXXXXXXXXXXXXXXXXXXXX iptables -t nat -I OUTPUT -d 1.2.3.4/32 -j DNAT --to-destination 192.168.0.10

This would put an IPtables rules in the NAT table for that particular network namespace.

**Comment by ldx** [comment]
This project: https://github.com/larsks/python-netns might help. I haven't tested it, but something like this:

    import netns

    with netns.NetNS(nsname='myns'):
        <use python-iptables here>

should work.

Let me know how it goes.

**Comment by RaginBajin** [comment]
Oh man... That works great.. Saved me a ton of time and parsing.. Thank you soooo much..

**Comment by hetii** [comment]
Hi,
Here is my solution based on pyroute2 package:

    from pyroute2 import NSPopen
    
    with NSPopen('your_namespace_name',['true']) as proc:
        <use python-iptables here>
