### ISSUE TITLE
problem while importing iptc

### ISSUE THREAD

**Issue by Tohichi** [ldx/python-iptables#170]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/iptc/__init__.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/iptc/ip4tc.py", line 13, in <module>
  File "build/bdist.linux-x86_64/egg/iptc/xtables.py", line 699, in <module>
AttributeError: 'NoneType' object has no attribute 'throw_exception'

**Comment by ldx** [comment]
How did you build/install python-iptables? This exception indicates the xtwrapper library is not found; it is created when python-iptables is built.

**Comment by davidmontgom** [comment]
I have the same issue.  I did via easy_install.  So what is the solution?

**Comment by ldx** [comment]
@davidmontgom can you tell me what OS, iptables and python-iptables versions you use? I'll try to repro it.

**Comment by Tohichi** [comment]
kali 2.0, iptables v1.4.21 and latest version of python-iptables. thanks.

**Comment by ldx** [comment]
Let me set up a VM and try to reproduce this.

**Comment by ldx** [comment]
@Tohichi does this:

    $ sudo python setup.py install_lib

fix the problem? It seems the native library is not installed when using just `sudo python setup.py install`.

**Comment by stinnux** [comment]
I had the same problem. running `python setup.py install_lib` solved it.

**Comment by ldx** [comment]
@Binsoma did you install the shared library via `python setup.py install_lib`?

**Comment by Binsoma** [comment]
@ldx No, I installed by using "sudo apt-get install python-setuptools python-dev git-core".
When I put python setup.py install_lib I get "python: can't open file 'setup.py': [Errno 2] No such file or directory"
Could you provide step by step installing using python setup.py install_lib, May be it could solve the above error. Thanks

**Comment by stinnux** [comment]
you need to run it in the python-iptables source directory.

**Comment by Binsoma** [comment]
Could you please specify where is this source directory.

**Comment by ldx** [comment]
@Binsoma did you clone the repo and installed from source, or from a package via pip or apt-get?

**Comment by Binsoma** [comment]
I used sudo apt-get install python-setuptools python-dev

**Comment by ldx** [comment]
@Binsoma and how about python-iptables itself? Did you install it from source, via pip with/without a virtualenv, or from apt?
