### ISSUE TITLE
Hi I am using this module in openwrt 15.05, I am getting following issue: raise XTablesError("can't find target %s" % (name)) iptc.xtables.XTablesError: can't find target DROP

### ISSUE THREAD

**Issue by Arun-Rajput** [ldx/python-iptables#176]

**Comment by Arun-Rajput** [comment]
following is the output of ls /lib/xtables
libipt_CLUSTERIP.so   libxt_NFLOG.so        libxt_iprange.so
libipt_DNAT.so        libxt_NFQUEUE.so      libxt_ipvs.so
libipt_ECN.so         libxt_SECMARK.so      libxt_length.so
libipt_LOG.so         libxt_SET.so          libxt_limit.so
libipt_MASQUERADE.so  libxt_SYNPROXY.so     libxt_mac.so
libipt_MIRROR.so      libxt_TCPMSS.so       libxt_mark.so
libipt_NETMAP.so      libxt_TCPOPTSTRIP.so  libxt_multiport.so
libipt_REDIRECT.so    libxt_TEE.so          libxt_nfacct.so
libipt_REJECT.so      libxt_TOS.so          libxt_osf.so
libipt_SAME.so        libxt_TPROXY.so       libxt_owner.so
libipt_SNAT.so        libxt_TRACE.so        libxt_physdev.so
libipt_ULOG.so        libxt_addrtype.so     libxt_pkttype.so
libipt_ah.so          libxt_bpf.so          libxt_policy.so
libipt_icmp.so        libxt_cluster.so      libxt_quota.so
libipt_realm.so       libxt_comment.so      libxt_rateest.so
libipt_ttl.so         libxt_connbytes.so    libxt_recent.so
libipt_unclean.so     libxt_connlabel.so    libxt_rpfilter.so
libxt_AUDIT.so        libxt_connlimit.so    libxt_sctp.so
libxt_CHECKSUM.so     libxt_conntrack.so    libxt_socket.so
libxt_CLASSIFY.so     libxt_cpu.so          libxt_standard.so
libxt_CONNMARK.so     libxt_dccp.so         libxt_statistic.so
libxt_CONNSECMARK.so  libxt_devgroup.so     libxt_string.so
libxt_CT.so           libxt_ecn.so          libxt_tcp.so
libxt_DSCP.so         libxt_esp.so          libxt_time.so
libxt_HMARK.so        libxt_hashlimit.so    libxt_u32.so
libxt_IDLETIMER.so    libxt_helper.so       libxt_udp.so
libxt_LED.so          libxt_id.so

**Comment by Arun-Rajput** [comment]
first i found xtables_version issue, somehow i resolved that after that i got "Can't find protocol" error,I resolved that too..but now i am getting this error, not able to resolve it, would you please help me out.

**Comment by ldx** [comment]
@Arun-Rajput can you tell me what version of iptables and python-iptables are installed on that box?

**Comment by ldx** [comment]
No reply, closing.
