### ISSUE TITLE
'Invalid argument' during hashlimit configuration

### ISSUE THREAD

**Issue by agalauner-r7** [ldx/python-iptables#179]
Hi,

I'm trying to use this library to implement a rate-limiting rule using hashlimit as follows:

    table = iptc.Table(iptc.Table.FILTER)
    table.autocommit = False

    input_chain = iptc.Chain(table, "INPUT")

    rule = iptc.Rule()
    rule.protocol = "tcp"

    conntrack_match = rule.create_match("conntrack")
    conntrack_match.ctstate = 'NEW'

    hashlimit_match = rule.create_match("hashlimit")
    hashlimit_match.hashlimit_name = 'dio'
    hashlimit_match.hashlimit_srcmask = '24'
    hashlimit_match.hashlimit_above = '1/minute'
    hashlimit_match.hashlimit_burst = '3'
    hashlimit_match.hashlimit_mode = 'srcip'

    target = rule.create_target("DROP")
    input_chain.insert_rule(rule)

    table.commit()

It is basically the equivalent to this iptables commandline:

	iptables -A INPUT \
	-m conntrack --ctstate NEW              \
	-m hashlimit --hashlimit-name dio  \
	           --hashlimit-srcmask 24     \
	           --hashlimit-above 1/minute \
	           --hashlimit-burst 3        \
	           --hashlimit-mode srcip     \
	-j DROP

During the commit I get the following error message:

      File "/usr/local/lib/python3.5/dist-packages/iptc/ip4tc.py", line 1561, in commit
        raise IPTCError("can't commit: %s" % (self.strerror()))
    iptc.ip4tc.IPTCError: can't commit: b'Invalid argument'

If I do not disable the autocommit btw, I do not get an error at all. The rule just doesn't show up in iptables.

Any ideas what could be wrong?

**Comment by ldx** [comment]
@agalauner-r7 can you try adding `hashlimit_match.hashlimit_htable_expire = '1000'` as a match parameter? That should fix your problem.

**Comment by agalauner-r7** [comment]
Thanks, that worked fine.
I think the default for that parameter is 10000 though instead of 1000, so I changed that for my code.

Thank you for your help!

**Comment by ldx** [comment]
Awesome!
