### ISSUE TITLE
How to call the final_check() to check a rule before inserting 

### ISSUE THREAD

**Issue by NevenLeung** [ldx/python-iptables#183]
I want to use the final_check() to check if a same rule is in the chain that i want to add a rule. If the rule exit, cancel the inserting, instead, insert it. If possible, can i get how many the same rule in the chain?

How can i do this, can someone explain the how the rule.final_check() of chain.delete_rule() works and tell me how to call final_check() correctly?
@ldx

**Comment by ldx** [comment]
Hey, `final_check()` is probably not what you're looking for here. You can just iterate through a chain and compare rules. Something like this should work:

```import iptc
table = iptc.Table(iptc.Table.FILTER)
table.autocommit = False
chain = iptc.Chain(table, "FORWARD")
for rule in chain.rules:
    # You can check rules here. This will check if "-o eth0" is used for the rule.
    if rule.out_interface and "eth0" in rule.out_interface:
        chain.delete_rule(rule)
table.commit()
table.autocommit = True
```

**Comment by NevenLeung** [comment]
Thanks, i think it is supposed to be a check function that can check is a same rule in a chain. Yes, i used such a way to delete the matched rules.

I used another approach to check if any the same rule as the matched one in the chain:

`import subprocess`
`subprocess.call(['iptables', '-C', 'INPUT', '-p' ,protocol, '-s', ip, '--dport', port, '-j', policy])`

using the iptables command in shell, but iptables of some linux may not have '-C' (check)option.
