### ISSUE TITLE
erratic results 

### ISSUE THREAD

**Issue by samnet** [ldx/python-iptables#184]
Hello dear ldx,

I m working on (dis)allowing some machine in my network to use the internet. 
 I have an issue with the allowFwd method below and I m not sure where the problem lies. This function is supposed to translate the instructions:
```
iptables -A FORWARD -s $IP_CLIENT -j ACCEPT
iptables -A FORWARD -d $IP_CLIENT -j ACCEPT
```
Simple enough...
The thing is, that running 
```
allowFwd(anIP) 
denyFwd(anIP)
allowFwd(anIP)
```
results in FORWARD successively looking like: 
```
root@slm:/home/slm# iptables -L FORWARD
Chain FORWARD (policy DROP)
target     prot opt source               destination         

root@slm:/home/slm# iptables -L FORWARD
Chain FORWARD (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             192.168.12.242      
ACCEPT     all  --  192.168.12.242       anywhere
     
root@slm:/home/slm# iptables -L FORWARD
Chain FORWARD (policy DROP)
target     prot opt source               destination   
      
root@slm:/home/slm# iptables -L FORWARD
Chain FORWARD (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             192.168.12.242
```
I.e., while the first call to allowFwd has created two rules, the second only created one rule. 
If I enter in the shell the iptables commands this function is supposed to translate however, two rules are created, as expected. 
Perhaps it is my code that is bad, but I m unable to understand what s going wrong. What do you think?

**hpUtils.py:**
```
import iptc
def allowFwd(anIP):
# allow all forwarding to/by a client on the network
        # iptables -A FORWARD -s $IP_CLIENT -j ACCEPT
        chain = iptc.Chain(iptc.Table(iptc.Table.FILTER), "FORWARD")
        rule = iptc.Rule()
        rule.src = anIP+"/255.255.255.255"
        target = iptc.Target(rule, "ACCEPT")
        rule.target = target
        chain.insert_rule(rule)
        # iptables -A FORWARD -d $IP_CLIENT -j ACCEPT
        rule2 = iptc.Rule()
        rule2.dst= anIP+"/255.255.255.255"
        target2 = iptc.Target(rule2, "ACCEPT")
        rule2.target = target2
        chain.insert_rule(rule2)


def denyFwd(anIP):
# get rid of all permissive exception concerning anIP
        table = iptc.Table(iptc.Table.FILTER)
        table.autocommit = False
        chain = iptc.Chain(table, "FORWARD")
        for rule in chain.rules:
                if rule.dst == anIP+'/255.255.255.255' or rule.src == anIP+'/255.255.255.255' :
                        chain.delete_rule(rule)
        table.commit()
        table.autocommit = True
```

**Comment by ldx** [comment]
Hey @samnet, did you manage to figure this one out?

**Comment by samnet** [comment]
Thx for this answer.
I was not able to have it work... I think that the issue had to do with the autocommit/commit() bits of denyFwd(). 
For the moment, I switched to the (not optimal) other way described in the doc: 

```
def denyFwd(anIP):
# get rid of all permissive exception concernign anIP
    table = iptc.Table(iptc.Table.FILTER)
    chain = iptc.Chain(table, "FORWARD")
    modified = True
    while modified:
        modified = False
        for rule in chain.rules:
            if anIP in rule.dst or anIP in rule.src :
                    chain.delete_rule(rule)
                modified = True
                break
```
it does behave well :). 

Thank you

**Comment by ldx** [comment]
Any chance you're touching iptables from multiple threads/processes? It's good practice to only do it from the same process and thread to make sure rule manipulations are synchronized.

**Comment by samnet** [comment]
Hello, 

apologies for late reply. Unfortunately, I am positive I was executing the above  code from within a single thread. 

As a side note, may I ask you how is concurrent editing of the tables handled? Is it taken care of in any way by the library, or is the programmer responsible for it?
You mention in the documentation that Table is a singleton. Can you explicit what you meant by that please? 

Thank you

**Comment by ldx** [comment]
Hey @samnet,

- Concurrent access from multiple threads is discouraged. Iptables itself uses a lock under the hood, so you will likely get an exception about a locking error when you try to do that.
- Table is a singleton:

    >>> import iptc
    >>> t1 = iptc.Table('nat')
    >>> t2 = iptc.Table('nat')
    >>> id(t1)
    139934100413264
    >>> id(t2)
    139934100413264
    >>>
