### ISSUE TITLE
python-iptables installation error

### ISSUE THREAD

**Issue by Pinsonbavard** [ldx/python-iptables#185]
Hi guys,

I am trying to install python-iptables using pip but I get the following error called "failed with exit status 2"

You can view the error message below. Thanks

![iptable-err](https://cloud.githubusercontent.com/assets/6134716/17077896/646b0326-5097-11e6-9970-975bbd933d5a.png)

**Comment by ldx** [comment]
Hey @Pinsonbavard, is this on Windows? Iptables is Linux only.

**Comment by Pinsonbavard** [comment]
Wow, thank you very much Idx

**Comment by Pinsonbavard** [comment]
So are you saying it will work on any Linux PC?

**Comment by ldx** [comment]
It supports a wide range of iptables versions. Let me know if something is not working on a Linux box, together with info on your distribution on iptables version.

**Comment by Pinsonbavard** [comment]
Okay, also what alternative can be used for Windows OS, do you have any in mind?

**Comment by ldx** [comment]
I have no idea, haven't used Windows in a long time. :)

**Comment by Pinsonbavard** [comment]
So to use a Linux OS as a beginner, suggest an  OS for me

**Comment by ldx** [comment]
You can give Ubuntu a try. :)

**Comment by Pinsonbavard** [comment]
Okay, thanks ldx
