### ISSUE TITLE
insert_rule missing

### ISSUE THREAD

**Issue by lemsx1** [ldx/python-iptables#186]
#182 I'm not sure if this is a global issue or just applying to my code, so bear with me...

I have a script that receives a list of subnets and ports to apply to an iptable chain. The chain is then referenced in FORWARD, and the user is able to use the services he/she was supposed to get...

The flow is like:

a. create new chain. Say: **tun0_lmondesi**
b. hook to FORWARD. Say: src and dst references to **tun0_lmondesi**. Example 

```
iptables -nL|grep lmondesi
tun0_lmondesi  all  --  0.0.0.0/0            10.x.x.43        
tun0_lmondesi  all  --  10.x.x.43         0.0.0.0/0           
Chain tun0_lmondesi (2 references)
# .
iptables -nL tun0_lmondesi|wc -l
128
```

c. use insert_rule() to insert rules to the chain

I expect all rules to be available in the new chain (tun0_lmondesi) but **the very first rule inserted is always missing**. The number of rules should've been 129, but it's always 128.

I've added plenty of logging before/after the insert of the rule, so I can see that it gets inserted. However, when the script is done the rule is no longer there! Note that as rules are inserted they get pushed down the chain as insert_rule() does that (and we are not appending). So, the very last rule from iptables -nL tun0_lmondesi should match the first rule from the array of subnets+ports.

If I add a dummy subnet to the array of subnets, the rule is added but the dummy is missing. If I run python interactively, I'm able to type all the same statements and the rule is added.

I also thought this was related to autocommit, so I turned off autocommit everywhere in the script, but still the rule does not show in **iptables -nL** even though it was supposedly inserted by python-iptables.

This has bugged me for days and I can't find an answer. I went from 0.4.0 to 0.10.0 trying to see if the problem was in python-iptables or my code.

Am I doing something wrong?

**Comment by ldx** [comment]
Can you also repro this with the latest version? Or using master from github?
