### ISSUE TITLE
feature request: quota

### ISSUE THREAD

**Issue by samnet** [ldx/python-iptables#188]
Hello,

a feature of iptables I found particularly useful to administer a Hotspot is the "quota" one. It acts as a ceiling on the traffic ( as detailed in http://linuxgazette.net/108/odonovan.html) and a typical quota rule looks like: 
`-A INPUT -p tcp -m quota --quota 123456 -j ACCEPT `.
I think it would be a super useful addition to python-iptables. 

rgds

**Comment by ldx** [comment]
Hi @samnet,

something like this should work:

```
import iptc

table = iptc.Table(iptc.Table.FILTER)
table.autocommit = False

input_chain = iptc.Chain(table, "INPUT")

rule = iptc.Rule()
rule.protocol = "tcp"

match = rule.create_match("quota")
match.quota = '123456'

target = rule.create_target("ACCEPT")

input_chain.insert_rule(rule)

table.commit()
```

**Comment by samnet** [comment]
Works perfectly, thanks.
