### ISSUE TITLE
import iptc

### ISSUE THREAD

**Issue by zokford** [ldx/python-iptables#189]
I am using python-iptables and do not have so many examples to go ahead with it, can you please guide me for some documentation to understand it ... thank you

**Comment by ldx** [comment]
Have you checked the readme? https://github.com/ldx/python-iptables/blob/master/README.md

**Comment by zokford** [comment]
Yes I did, are there any advanced docs please ?

**Comment by ldx** [comment]
I'm afraid there are no docs like that.

Do you have any specific question, or anything you think is missing from the docs?
