### ISSUE TITLE
Timeout on create_target()

### ISSUE THREAD

**Issue by genslow** [ldx/python-iptables#190]
I have a script that uses the IPTables package to modify my firewall rules. At one point, this code was working fine. Now, however, it times out on the call to create_target() hangs. No exception is thrown, the process just ends.

Here's my code:

```
table = iptc.Table(iptc.Table.FILTER)
chain = iptc.Chain(table, CHAIN_FORWARD)
clientRule = iptc.Rule()
clientRule.in_interface = TAP_IF
clientRule.src = clientIp
clientRule.dst = wpIp
clientRule.target = clientRule.create_target("ACCEPT")
if clientRule not in chain.rules:
    chain.append_rule(clientRule)
```

Any suggestions?
-Greg

**Comment by ldx** [comment]
Hey @genslow, is it hanging, or the python process exiting? Might be a crash.
