### ISSUE TITLE
Example for inverse ipset match

### ISSUE THREAD

**Issue by dadittoz** [ldx/python-iptables#191]
Could someone help me with an example on how to do a inverse ipset match? I googled to no avail.
Something like this can be done in command line:

```
iptables -t mangle -A MYCHAIN_OUT -m set ! --match-set localnet src -j RETURN
```

I have the following code, so you could quickly add exclamation mark somewhere in it ;)

``` python
mangle_table = iptc.Table(iptc.Table.MANGLE)
c = iptc.Chain(mangle_table, 'MYCHAIN_OUT')
r = iptc.Rule()
m = r.create_match("set")
m.match_set = ['localnet', 'src']
r.target = iptc.Target(r, 'RETURN')
c.insert_rule(r)
```

Since this should be an issue rather than a support request, I would suggest adding such an example to FAQ.

**Comment by jllorente** [comment]
Hi, did you try with  this ?
```
m.match_set ='!test src'
```

**Comment by jllorente** [comment]
I found the way :)
```
m.match_set = ['!', 'test', 'src']
```

**Comment by ldx** [comment]
Thanks!
