### ISSUE TITLE
ipset / libipset?

### ISSUE THREAD

**Issue by pepoluan** [ldx/python-iptables#197]
Hi!

Do you have plans on providing a Pythonic interface to ipset (libipset), too?

If not, do you have a recommendation on a module that does to libipset what yours do to libiptc?

**Comment by ldx** [comment]
Hey @pepoluan,

I've never used libipset and currently I have limited free time, so I don't plan to start a new project. :)

This is one project I found: https://github.com/Lukasa/python-ipset but not sure how well it works.

Cheers!

**Comment by jllorente** [comment]
Hei @pepoluan, maybe you want to try this one out :)
https://github.com/svinota/pyroute2
