### ISSUE TITLE
DNAT corrupted double-linked list

### ISSUE THREAD

**Issue by gummeah** [ldx/python-iptables#216]
Hello.
I'm getting error:

>  *** Error in `python3.6': corrupted double-linked list: 0x0000000001dcdf30 ***

When trying to do this:
```
docker_nat = iptc.Chain(iptc.Table(iptc.Table.NAT), 'DOCKER')
for rule in docker_nat.rules:
    if rule.dst == '192.168.1.2/255.255.255.255':
        for match in rule.matches:
            if match.parameters['dport'] == '5022':
                rule.target.set_parameter('to_destination', '127.0.0.1:22')
```
Am I doing something wrong or is that some sort of a bug?
Thanks.

Python 3.6.2 (default, Jul 18 2017, 22:59:45)
python-iptables (0.12.0)
ldd (GNU libc) 2.17

**Comment by ldx** [comment]
This looks like a bug. Any chance you can also copy/paste the rules for the NAT table from `iptables-save` so I can try to reproduce it?

**Comment by gummeah** [comment]
I can't reproduce this error :/ I have not changed anything, except for iptables entries maybe, and it works now.  I'll try to capture iptables entries and let you know if it will happen again.

**Comment by jllorente** [comment]
In that snippet you are not checking the target is indeed DNAT, where to perform "to_destination".
Could it be that the rule you are reading does not have such target and just behaves as a packet counter? I have sometimes used this approach to light weight debugging, instead of TRACE  :)

As @ldx mentioned, if you could provide the rules it would help a lot

**Comment by zakatsv** [comment]
I have an issue with python-iptables (version 0.14.0 installed with pip)
When I try to set target parameter for DNAT formatted as <ip>:<port>, it fails.
When I specify IP only, the issue does not occur.

>>> import iptc
>>> rule = iptc.Rule()
>>> target = iptc.Target(rule, "DNAT")
>>> target.set_parameter('to_destination', '127.0.0.1:8080')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/restvpn2/env/lib/python3.6/site-packages/iptc/ip4tc.py", line 285, in set_parameter
    return self.parse(parameter.replace("_", "-"), value)
  File "/opt/restvpn2/env/lib/python3.6/site-packages/iptc/ip4tc.py", line 332, in parse
    self._parse(argv, inv, entry)
  File "/opt/restvpn2/env/lib/python3.6/site-packages/iptc/ip4tc.py", line 793, in _parse
    self._orig_parse, self._orig_options)
  File "/opt/restvpn2/env/lib/python3.6/site-packages/iptc/xtables.py", line 869, in new
    return fn(*args)
  File "/opt/restvpn2/env/lib/python3.6/site-packages/iptc/xtables.py", line 1123, in parse_target
    argv[1]))
iptc.errors.XTablesError: b'DNAT': parameter error -2 (b'127.0.0.1:8080')

Any help would be appreciated.

**Comment by ldx** [comment]
@zakatsv try setting the protocol for your rule:

    import iptc
    rule = iptc.Rule()
    rule.protocol = 'tcp'
    target = iptc.Target(rule, "DNAT")
    target.set_parameter('to_destination', '127.0.0.1:8080')

**Comment by zakatsv** [comment]
@ldx Thank you very much for the blazing fast response. It worked as a charm!
