### ISSUE TITLE
Error installing on Raspberry Pi (Raspbian Jessie)

### ISSUE THREAD

**Issue by jee1mr** [ldx/python-iptables#217]
running install
running bdist_egg
running egg_info
writing python_iptables.egg-info/PKG-INFO
writing top-level names to python_iptables.egg-info/top_level.txt
writing dependency_links to python_iptables.egg-info/dependency_links.txt
reading manifest file 'python_iptables.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README'
warning: no files found matching 'test.py'
writing manifest file 'python_iptables.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
running build_ext
building 'libxtwrapper' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c libxtwrapper/wrapper.c -o build/temp.linux-armv7l-2.7/libxtwrapper/wrapper.o
libxtwrapper/wrapper.c:96:1: internal compiler error: Segmentation fault
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Preprocessed source stored into /tmp/ccFy1FE1.out file, please attach this to your bugreport.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

`arm-linux-gnueabihf-gcc (Raspbian 4.9.2-10) 4.9.2`

**Comment by ldx** [comment]
This looks like a compiler bug. Can you try installing a different compiler version?

**Comment by jee1mr** [comment]
I thought so too. But it's compiling with the same gcc version on a different RPi. Let me check again.
