### ISSUE TITLE
iterate chain.rules and get dst_port and src_port from a rule

### ISSUE THREAD

**Issue by ivanlmj** [ldx/python-iptables#218]
According to this [document](https://github.com/ldx/python-iptables/blob/master/README.md):

You can of course also check what a rule's source/destination address, in/out inteface etc is. To print out all rules in the FILTER table:

>>> import iptc
>>> table = iptc.Table(iptc.Table.FILTER)
>>> for chain in table.chains:
>>>     print "======================="
>>>     print "Chain ", chain.name
>>>     for rule in chain.rules:
>>>         print "Rule", "proto:", rule.protocol, "src:", rule.src, "dst:", \
>>>               rule.dst, "in:", rule.in_interface, "out:", rule.out_interface,
>>>         print "Matches:",
>>>         for match in rule.matches:
>>>             print match.name,
>>>         print "Target:",
>>>         print rule.target.name
>>> print "======================="

Is that possible to also obtain the Destination and Source Port from a rule?

**Comment by jllorente** [comment]
Yes it is. you need to access the attribute with the protocol at hand, for example
if match.name in ('tcp', 'udp'):
    print((match.sport, match.dport))

**Comment by ivanlmj** [comment]
Thanks, @jllorente :+1: !

**Comment by jllorente** [comment]
With the new _iptc.easy_ module you could use the _dump_ functions like this:

```
$ sudo python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iptc
>>> iptc.easy.dump_
iptc.easy.dump_all(    iptc.easy.dump_chain(  iptc.easy.dump_table(
>>> iptc.easy.dump_all()
{'mangle': {'INPUT': [], 'OUTPUT': [], 'PREROUTING': [], 'FORWARD': [], 'POSTROUTING': []}, 'nat': {'INPUT': [], 'OUTPUT': [], 'PREROUTING': [], 'POSTROUTING': []}, 'raw': {'OUTPUT': [], 'PREROUTING': []}, 'filter': {'INPUT': [], 'OUTPUT': [], 'FORWARD': [{'in-interface': 'enp3s0', 'target': 'ACCEPT', 'state': {'state': 'RELATED,ESTABLISHED'}, 'out-interface': 'enp3s1'}]}, 'security': {'INPUT': [], 'OUTPUT': [], 'FORWARD': []}}
```
