### ISSUE TITLE
Instead of creating a new Chain instance, the previous one with the same name gets reused

### ISSUE THREAD

**Issue by Feliksas** [ldx/python-iptables#224]
In [1]: import iptc

In [2]:  t_filter = iptc.Table(iptc.Table.FILTER)

In [3]: t_filter6 = iptc.Table6(iptc.Table6.FILTER)

In [4]: t_filter
Out[4]: <iptc.ip4tc.Table at 0x7f2af10c62d0>

In [5]: t_filter6
Out[5]: <iptc.ip6tc.Table6 at 0x7f2af3b12d90>

In [6]: c_input = iptc.Chain(t_filter, 'INPUT')

In [7]: c_input
Out[7]: <iptc.ip4tc.Chain at 0x7f2af3abf410>

In [8]: c_input6 = iptc.Chain(t_filter6, 'INPUT')

In [9]: c_input6
Out[9]: <iptc.ip4tc.Chain at 0x7f2af3abf410>

even the deletion doesn't help:

In [10]: del c_input

In [11]: c_input6
Out[11]: <iptc.ip4tc.Chain at 0x7f2af3abf410>

In [12]: del c_input6

In [13]: c_input6 = iptc.Chain(t_filter6, 'INPUT')

In [14]: c_input6
Out[14]: <iptc.ip4tc.Chain at 0x7f2af3abf410>

Python 2.7.14, python-iptables 0.12.0

**Comment by Feliksas** [comment]
Clarification: I'd like to create a chain with the same name in both iptables and ip6tables, and fill them both in the same cycle from a single hosts source (say, list or set). It turns out that it is impossible, as a Chain object with a given name gets instantiated only once (is it a singleton like Table?)

**Comment by ldx** [comment]
@Feliksas I created a branch called `issue224`, can you give it a try and see if it fixes your issue? It now creates separate instances for IPv4 vs IPv6 chains for me.

**Comment by codecat555** [comment]
FYI - I ran into the same problem and this branch is working well for me. Thanks!

**Comment by ldx** [comment]
Thanks, I merged that branch.
