### ISSUE TITLE
Cannot create a rule to match manually-created rules

### ISSUE THREAD

**Issue by codecat555** [ldx/python-iptables#230]
I'm looking for a compact method to find a specific rule in a chain. I tried to do this by creating a rule with certain characteristics and then running:

    idx = chain.rules.index(rule)

This approach fails because the equality test fails in the Match class. The following code illustrates the problem:

```
import iptc

table = iptc.Table(iptc.Table.FILTER)
chain = iptc.Chain(table, 'RH-Firewall-1-INPUT')

m1 = chain.rules[5].matches[0]
print 'm1: name=%s, state=%s, match.u.user.name=%s' % (m1.name, m1.state, m1.match.u.user.name)

m2 = iptc.Match(chain.rules[5], name='state')
m2.state = 'NEW'
print 'm2: name=%s, state=%s, match.u.user.name=%s' % (m2.name, m2.state, m2.match.u.user.name)

if m1 == m2:
    print "m1 is not equal to m2"
else:
    print "m1 is not equal to m2"

```
On my system, this code prints:

```
m1: name=state, state=NEW, match.u.user.name=state
m2: name=state, state=NEW, match.u.user.name=conntrack
m1 is not equal to m2

```
This is on a Centos 7 system running kernel version 3.10.0-693.2.2.el7 and iptables-1.4.21-16.el7.x86_64.

The 'conntrack' value is coming from these lines in Match.__init__:

```
module = self._xt.find_match(name)
real_name = module and getattr(module[0], 'real_name', None) or None

```

**Comment by ldx** [comment]
@codecat555 can you show me the offending rule (e.g. the output from `iptables-save`)?

**Comment by codecat555** [comment]
`-A RH-Firewall-1-INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
`

**Comment by jllorente** [comment]
@codecat555  perhaps the comparison of Match() could be a little bit different - https://github.com/ldx/python-iptables/blob/master/iptc/ip4tc.py#L575

On a side note and regarding best practice, the state module is deprecated in favor of conntrack
https://superuser.com/questions/1071656/whats-the-difference-between-iptables-state-and-ctstate

**Comment by jllorente** [comment]
I have created a PR to address this issue, https://github.com/ldx/python-iptables/pull/272

**Comment by jllorente** [comment]
The fix is now available in master
