### ISSUE TITLE
Import iptc issue

### ISSUE THREAD

**Issue by Van-hoa** [ldx/python-iptables#235]
Hi,

I wanted to use python-iptables package for build a firewall.
Unfortunately, when i tried to import iptc into my Python scripts, i have an error "
iptc.xtables.XTablesError: can't find directory with extensions; please set XTABLES_LIBDIR" when i run my code but python-iptables is in "Project Interpreter" and the package is in /usr/lib/x86_64-linux-gnu/xtables" so i can't figure out why it doesn't work, maybe you can help me ?

Thank's.

N.B : I use PyCharm.

**Comment by ldx** [comment]
@Van-hoa can you tell me what distribution type and version you use, and how you installed python-iptables?

**Comment by Van-hoa** [comment]
I used a distrib based on Debian named ParrotSecurity. I installed python-iptables via the pip command.

**Comment by Van-hoa** [comment]
No ideas?

**Comment by Van-hoa** [comment]
1) It works from the command line. But i need to use it within a script (it's a project for my studies).

3) I checked and there is no .so file like "iptables.so" or something like that.

**Comment by ldx** [comment]
On Debian or on most Debian based systems it should be something like this:

```$ ls /usr/lib/x86_64-linux-gnu/xtables
libip6t_ah.so          libipt_realm.so       libxt_ecn.so        libxt_RATEEST.so
libip6t_DNAT.so        libipt_REDIRECT.so    libxt_esp.so        libxt_recent.so
libip6t_DNPT.so        libipt_REJECT.so      libxt_hashlimit.so  libxt_rpfilter.so
libip6t_dst.so         libipt_SNAT.so        libxt_helper.so     libxt_sctp.so
libip6t_eui64.so       libipt_ttl.so         libxt_HMARK.so      libxt_SECMARK.so
libip6t_frag.so        libipt_TTL.so         libxt_IDLETIMER.so  libxt_set.so
libip6t_hbh.so         libipt_ULOG.so        libxt_ipcomp.so     libxt_SET.so
libip6t_hl.so          libxt_addrtype.so     libxt_iprange.so    libxt_socket.so
libip6t_HL.so          libxt_AUDIT.so        libxt_ipvs.so       libxt_standard.so
libip6t_icmp6.so       libxt_bpf.so          libxt_LED.so        libxt_state.so
libip6t_ipv6header.so  libxt_cgroup.so       libxt_length.so     libxt_statistic.so
libip6t_LOG.so         libxt_CHECKSUM.so     libxt_limit.so      libxt_string.so
libip6t_MASQUERADE.so  libxt_CLASSIFY.so     libxt_mac.so        libxt_SYNPROXY.so
libip6t_mh.so          libxt_cluster.so      libxt_mangle.so     libxt_tcpmss.so
libip6t_NETMAP.so      libxt_comment.so      libxt_mark.so       libxt_TCPMSS.so
libip6t_REDIRECT.so    libxt_connbytes.so    libxt_MARK.so       libxt_TCPOPTSTRIP.so
libip6t_REJECT.so      libxt_connlabel.so    libxt_multiport.so  libxt_tcp.so
libip6t_rt.so          libxt_connlimit.so    libxt_nfacct.so     libxt_TEE.so
libip6t_SNAT.so        libxt_connmark.so     libxt_NFLOG.so      libxt_time.so
libip6t_SNPT.so        libxt_CONNMARK.so     libxt_NFQUEUE.so    libxt_tos.so
libipt_ah.so           libxt_CONNSECMARK.so  libxt_NOTRACK.so    libxt_TOS.so
libipt_CLUSTERIP.so    libxt_conntrack.so    libxt_osf.so        libxt_TPROXY.so
libipt_DNAT.so         libxt_cpu.so          libxt_owner.so      libxt_TRACE.so
libipt_ECN.so          libxt_CT.so           libxt_physdev.so    libxt_u32.so
libipt_icmp.so         libxt_dccp.so         libxt_pkttype.so    libxt_udp.so
libipt_LOG.so          libxt_devgroup.so     libxt_policy.so
libipt_MASQUERADE.so   libxt_dscp.so         libxt_quota.so
libipt_NETMAP.so       libxt_DSCP.so         libxt_rateest.so
```

Is it different for you?

**Comment by Van-hoa** [comment]
There is something like that.

**Comment by ldx** [comment]
I just checked, the problem seems to be that the last release does not have `/usr/lib/x86_64-linux-gnu/xtables` in the search path when it's trying to find extensions.

There are a couple of ways to work around this:
- Install python-iptables from source instead of via pip.
- Make sure you `export XTABLES_LIBDIR=/usr/lib/x86_64-linux-gnu/xtables` before you start PyCharm.
- Export this environment variable in your code before importing iptc, e.g.:

    os.environ["XTABLES_LIBDIR"] = "/usr/lib/x86_64-linux-gnu/xtables"
    import iptc

**Comment by andryyy** [comment]
On Alpine 3.7 I get the same error. I define "XTABLES_LIBDIR=/usr/lib/xtables" (the actual directory) and it fails with:

```
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/server.py", line 14, in <module>
netfilter-mailcow_1  |     import iptc
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/__init__.py", line 10, in <module>
netfilter-mailcow_1  |     from iptc.ip4tc import (is_table_available, Table, Chain, Rule, Match, Target, Policy, IPTCError)
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 40, in <module>
netfilter-mailcow_1  |     xtables(NFPROTO_IPV4)
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/xtables.py", line 933, in __new__
netfilter-mailcow_1  |     obj._xtinit(proto)
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/xtables.py", line 948, in _xtinit
netfilter-mailcow_1  |     (xtables_version))
netfilter-mailcow_1  | iptc.errors.XTablesError: unknown xtables version 0
```

**Comment by umlaeute** [comment]
@Van-hoa btw, there are Debian packages `python3-iptables` (or `python-iptables` if you are *still* using Python2 - which you shouldn't).

The Debian package is slightly patched to search the multi-arch path of xtables.

@andryyy this seems to be unrelated to this issue (although the subject line matches). i guess you should open a new ticket. Probably @ldx could change the title (of *this* issue) to something more meaningful like "imporing fails if xtables is in a multi-arch directory")

**Comment by ldx** [comment]
> The Debian package is slightly patched to search the multi-arch path of xtables.

@umlaeute can you point me to those patches? Thanks!

**Comment by ldx** [comment]
@andryyy can you please create a new issue? Your problem is likely something different from the one discussed in this thread. Thanks!

**Comment by umlaeute** [comment]
@ldx all Debian specific patches can be found [here](https://salsa.debian.org/python-team/modules/python-iptables/tree/debian/master/debian/patches).

However, note that the xtables-patch (`0002-...`) is rather simplistic, as it only has do deal with linux (and freebsd and hurd,...) and not care about Darwin and/or W32. That's also the main reason why I never forwarded the patch.

afaict, the other multi-arch related patch (`0003-...`) should be applicable  as is.

**Comment by andryyy** [comment]
@ldx I just came across this issue again, sorry for not reporting back. My issue was solved by adding some ENV vars. :-)

**Comment by Mr-HongHaiNguyen** [comment]
@andryyy : Can you share what were ENV vars you set to solve this issue? I have the same issue you described. Thanks!

**Comment by umlaeute** [comment]
@Mr-HongHaiNguyen probably those found here: https://github.com/ldx/python-iptables#using-a-custom-iptables-install

**Comment by leond08** [comment]
@Mr-HongHaiNguyen what did you do to solve your problem? I'am currently facing the same issue my environment is buildroot also. I'm having an error in importing iptc

**Comment by Mr-HongHaiNguyen** [comment]
@leond08 : It's quite long time ago, so I don't really remember how I fixed it. However I found this code snippet, hope it help:
```
for xtdir in ["/lib/xtables", "/usr/lib/xtables", "/usr/local/lib/xtables"]:
    if os.path.isdir(xtdir):
        os.environ['XTABLES_LIBDIR'] = xtdir
        break
try:
    import iptc
except:
    sys.exit("python-iptables isn't installed.")
```
