### ISSUE TITLE
ImportError: cannot import name version

### ISSUE THREAD

**Issue by BrianErikson** [ldx/python-iptables#236]
Greetings,

I have yet another import error. I'm running python 2.7.14 with python-iptables 0.12.0, installed by pip 9.0.1. I've tried uninstalling pip, deleting the cache, and re-installing pip and iptables through it, but I can't seem to get around the issue. running the python interpreter as sudo produces the same result. pip seems to work with other packages just fine. Please see below:

![iptc_error](https://user-images.githubusercontent.com/7645647/38837234-692f7b50-418e-11e8-9df8-dbd3b7ae17a6.png)

Thanks for any help that may be provided.

**Comment by ldx** [comment]
I just uploaded a new release to PyPi, can you give it a try?

**Comment by BrianErikson** [comment]
It's working great now -- thanks for your quick support and for the library.
