### ISSUE TITLE
How get position (rulenum) of a rule

### ISSUE THREAD

**Issue by nassimabedi** [ldx/python-iptables#243]
Hi,

How get position of a rule or rulenum and then replace with another rule?

Thanks

**Comment by nassimabedi** [comment]
Thank you for reply.
I know about `replace_rule`. 
I want to view all of rules with rule number in a chain to choose a rule with rule num (position) and replace with new rule.

**Comment by ldx** [comment]
You can iterate through chains like this:

```import iptc

T = iptc.Table('filter')
C = iptc.Chain(T, 'INPUT')
for i, rule in enumerate(C.rules):
    print i, rule.src, rule.dst, rule.protocol, \
            [m.get_all_parameters() for m in rule.matches], \
            rule.target.get_all_parameters()
```

**Comment by nassimabedi** [comment]
Thank you :)
