### ISSUE TITLE
When using match.state = "RELATED,ESTABLISHED" it is possible to insert the same rule into chain.

### ISSUE THREAD

**Issue by hetii** [ldx/python-iptables#246]
Hello
I use such simple contex manager class and method that use it:

	import iptc

	class RuleAdd():
	    def __init__(self, table_name, chain_name, target_name):
	        self.table_name = table_name
	        self.chain_name = chain_name
	        self.target_name = target_name

	    def __enter__(self):
	        table = iptc.Table(self.table_name)
	        self.chain = iptc.Chain(table, self.chain_name)
	        self.rule = iptc.Rule(chain=self.chain)
	        self.rule.create_target(self.target_name)
	        return self.rule

	    def __exit__(self, type, value, traceback):
	        if self.rule not in self.chain.rules:
	            self.chain.insert_rule(self.rule)
	        # This is small bug that I discover.
	        # Tables used by rules keep opened sockets
	        # and because of that namespaces are not truely removed.
	        # Thats why I close all tables and clear internal cache that hold them!
	        for table in self.rule.tables:
	            table.close()
	        table._cache.clear()

	def set_forward_related(owner, in_interface=None, out_interface=None):
	    # Examples:
	    # set_forward_related("foo", "enp3s0", "enp3s1")
	    with RuleAdd("filter", "FORWARD", "ACCEPT") as rule:
	        if in_interface is not None:
	            rule.in_interface = in_interface
	        if out_interface is not None:
	            rule.out_interface = out_interface
	        match = rule.create_match("state")    # when have this two lines i`m able to put
	        match.state = "RELATED,ESTABLISHED"   # the same multiple rules for this chain.
	        match = rule.create_match("comment")
	        match.comment = "owner: %s" % owner

Now by calling 3 times:

	set_forward_related("foo", "enp3s1", "enp3s1")
	set_forward_related("foo", "enp3s1", "enp3s1")
	set_forward_related("foo", "enp3s1", "enp3s1")

We see in iptables:

	-A FORWARD -i enp3s1 -o enp3s1 -m state --state RELATED,ESTABLISHED -m comment --comment "owner: foo" -j ACCEPT
	-A FORWARD -i enp3s1 -o enp3s1 -m state --state RELATED,ESTABLISHED -m comment --comment "owner: foo" -j ACCEPT
	-A FORWARD -i enp3s1 -o enp3s1 -m state --state RELATED,ESTABLISHED -m comment --comment "owner: foo" -j ACCEPT

But when just commenting out:

	# match = rule.create_match("state")
	# match.state = "RELATED,ESTABLISHED"

I can call multiple time set_forward_related() and only one rule is added.

**Comment by jllorente** [comment]
Related to https://github.com/ldx/python-iptables/issues/230

**Comment by jllorente** [comment]
@hetii , the problem is in the comparison of Match() instances. PR https://github.com/ldx/python-iptables/pull/272 addresses this :)

**Comment by jllorente** [comment]
The fix is now available in master
