### ISSUE TITLE
find overlap other rules

### ISSUE THREAD

**Issue by nassimabedi** [ldx/python-iptables#248]
Hi,

I am looking for a way to find overlap rules. I mean when insert a new rule if it overlap other rules
it returns me a notice. For example when I insert a rule to block a Port(8001) after that when I want to insert a rule that  allow that Port(8001) it returns a notice.

Thank you

**Comment by jllorente** [comment]
Hi @nassimabedi , that logic you can implement yourself without too much trouble.

For example:
- Get all rules in a chain
- For each rule, check if your target rule is included by the existing rule.

Initially, you could stick to checking a 5-tuple rule, that is (src_ip, dst_ip, proto, src_port, dst_port). From there onwards, you can extend to checking other _matches_ (iptables has quite a large number of them).

In any case, this project provides Python bindings to iptables, the logic you seek should reside in your code :)

**Comment by nassimabedi** [comment]
Hi @jllorente, Thank you for reply :)
