### ISSUE TITLE
Add support for IGMP protocol

### ISSUE THREAD

**Issue by konrad-fil** [ldx/python-iptables#250]
to reproduce:

```
test_rule = iptc.Rule()
test_rule.protocol= 'igmp'
```

raises ValueError: invalid protocol igmp

Protocols present in ip4tc.py are:
tcp, udp, icmp, esp, ah

**Comment by ldx** [comment]
@konrad-fil did you figure out what was wrong?

**Comment by konrad-fil** [comment]
@ldx Apparently our mirror contains python-iptables only up to release 0.3.0 so every time application was build that old version was bundled with it.
Because i spoted IGMP protocol in this very repository in the ip4tc.py that made me think 'Hey, something is wrong'
Maybe this is related with that release 0.3.0(year 2014) is still shown as latest relese
