### ISSUE TITLE
SIGABRT in create_chain if name length greater or equal to 30

### ISSUE THREAD

**Issue by konrad-fil** [ldx/python-iptables#252]
To reproduce:
```
import iptc
chain = iptc.Table('mangle').create_chain('mcastapp:PREROUTING:block_group')
```
if name is 29-30 characters long SIGABRT will be raised
if name is longer IPTCError will be thrown with message: "can't create chain mcastapp:PREROUTING:block_group123456789: Invalid argument"

**Comment by jllorente** [comment]
@konrad-fil , I don't think this is related to the library itself. The length of the iptable components, say chains, targets or matches, seems to be defined in the kernel. See [here](https://elixir.bootlin.com/linux/v4.14/source/include/uapi/linux/netfilter/x_tables.h#L7 )
