### ISSUE TITLE
Why can't I get the value of --state

### ISSUE THREAD

**Issue by hulengjing** [ldx/python-iptables#253]
How can I get the information in --state through python-iptables, now I can only add the settings, but I can't view the state when I traverse the rules.
eg: ipatbles -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

**Comment by jllorente** [comment]
@hulengjing , as of version 0.14 there is a new module added called iptc.easy (see the README for more information about this module).
You can either use it as a replacement of the low level interface provided by iptc or as a simple debugging tool for your iptc code for rules, targets, etc. See the following example:

```
# iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
# python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iptc
>>> iptc.easy.dump_chain('filter', 'INPUT')
[{'target': 'ACCEPT', 'state': {'state': 'RELATED,ESTABLISHED'}}]
>>> rule_d = iptc.easy.dump_chain('filter', 'INPUT')[0]
>>> rule = iptc.easy.encode_iptc_rule(rule_d)
<iptc.ip4tc.Rule object at 0x7fc88f466dd8>
>>> rule.matches[0].parameters
{'state': 'RELATED,ESTABLISHED'}
>>> rule.matches[0].state
'RELATED,ESTABLISHED'
```
