### ISSUE TITLE
log target

### ISSUE THREAD

**Issue by iomari** [ldx/python-iptables#256]
greetings,
how do i create a log target rule like "-j LOG--log-prefix "some text''"?

**Comment by ldx** [comment]
This should work:

    import iptc
    
    table = iptc.Table(iptc.Table.FILTER)
    table.refresh()
    default_chain = iptc.Chain(table, 'INPUT')
    rule = iptc.Rule()
    rule.protocol = 'tcp'
    rule.target = iptc.Target(rule, 'LOG')
    rule.target.log_prefix = "some text"
    default_chain.insert_rule(rule)
