### ISSUE TITLE
Code length 

### ISSUE THREAD

**Issue by iomari** [ldx/python-iptables#257]
Greetings, 
I'm really enjoying this module. I love codng. But I have an honest question/observation.
I have many iptables scripts that I've written in python using subprocess calls. Some of them quite complex. However when I converted a few of my smaller scripts, the iptc versions were much larger. That's the observation. The question is, is iptc more efficient than subprocess calls that justify the much larger scripts? And I mean MUCH larger. I've had as many as 10 iptc lines to 1 subprocess line.

**Comment by ldx** [comment]
It depends on the use case. If you only need something simple, e.g. inserting a rule or two when your application starts up, it's easier to shell out and call iptables. If you need to update rules in a very dynamic fashion, parse rules, etc, it's faster and more reliable to use a library (no process creation overhead, you don't have to create a parser for rules yourself, etc).

**Comment by jllorente** [comment]
Hi @iomari , please check the new _iptc.easy_ module that was recently added.
You can have one liners with iptables rules defined as python dictionaries :) 

```
$ sudo iptables -A FORWARD -p udp --dport 53 -d 8.8.8.8 -m comment --comment "Outgoing queries to Google DNS" -m conntrack --ctstate "NEW" -j ACCEPT

$ sudo python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iptc
>>> iptc.easy.dump_chain('filter', 'FORWARD')
[{'udp': {'dport': '53'}, 'target': 'ACCEPT', 'comment': {'comment': 'Outgoing queries to Google DNS'}, 'conntrack': {'ctstate': 'NEW'}, 'protocol': 'udp', 'dst': '8.8.8.8/32'}]
>>> iptc.easy.add_rule('filter', 'FORWARD', {'udp': {'sport': '53'}, 'target': 'DROP', 'comment': {'comment': 'Bogus response from Google DNS'}, 'conntrack': {'ctstate': 'INVALID'}, 'protocol': 'udp', 'src': '8.8.8.8/32'})
```

**Comment by jllorente** [comment]
Hi @iomari , did you have a chance to take a look at the comment above?
