### ISSUE TITLE
To-source

### ISSUE THREAD

**Issue by iomari** [ldx/python-iptables#259]
Greetings, 
chain = iptc.Chain(iptc.Table('nat'), 'POSTROUTING')
rule = iptc.Rule()
rule.protocol = 'tcp'
rule.out_interface = INTIF
target = iptc.Target(rule, 'SNAT')
target.to_source = GWIP
chain.insert_rule(rule)

The above code gives me an invalid number rule error on the last line. 
INTIF and GWIP are both elsewhere in the code and are used many times without error so I don't believe they're the issue.

**Comment by ldx** [comment]
The target you create is not attached to the rule. This should work:

    rule.target = iptc.Target(rule, 'SNAT')
    rule.target.to_source = GWIP

**Comment by iomari** [comment]
Thanks. That did it to 😀

**Comment by iomari** [comment]
Sorry, I spoke to soon. 
The error is gone but the rule is not appearing. 

chain = iptc.Chain(iptc.Table('nat'), 'POSTROUTING')
rule = iptc.Rule()
rule.protocol = 'tcp'
rule.out_interface = INTIF
rule.target = iptc.Target(rule, 'SNAT')
rule.target.to_source = GWIP
chain.insert_rule(rule)

**Comment by iomari** [comment]
Embarrassing. It works. I was flushing rules after the above lines.
