### ISSUE TITLE
Subnets aren't simplified

### ISSUE THREAD

**Issue by multun** [ldx/python-iptables#260]
When adding a rule with, for example, source subnet src = `10.42.15.12/20`, python-iptables doesn't simplify the subnet to `10.42.0.0/20`, which causes netfilter to brainfart and not match anything at all.

Is it somehow intended ?

**Comment by ldx** [comment]
Can you show me some example code?

**Comment by multun** [comment]
```py
import iptc
filter=iptc.Table('filter')
input={c.name: c for c in filter.chains}['INPUT']
new_rule = iptc.Rule()
new_rule.src = '1.2.3.4/20'
new_rule.target = iptc.Target(new_rule, "LOG")
input.append_rule(new_rule)
```

`iptables-save | grep 1\.2\.3\.4` =>  
`-A INPUT -s 1.2.3.4/20 -j LOG`

That rule seemingly can't be removed using -D:
```sh
$ iptables -D INPUT -s 1.2.3.4/20 -j LOG
iptables: No chain/target/match by that name.
$ iptables -A INPUT -s 1.2.3.4/20 -j LOG
$ iptables-save | grep 1\.2\..\..
-A INPUT -s 1.2.3.4/20 -j LOG
-A INPUT -s 1.2.0.0/20 -j LOG
$ iptables -D INPUT -s 1.2.3.4/20 -j LOG
```

**Comment by jllorente** [comment]
Hi @multun  thank you for spotting this!
I have submited PR https://github.com/ldx/python-iptables/pull/274 to address this issue.

**Comment by jllorente** [comment]
The fix is now available in master
