### ISSUE TITLE
Can't delete rule with IPSec policy match

### ISSUE THREAD

**Issue by TearsDontFalls** [ldx/python-iptables#261]
Hi,
loving the lib, but I noticed one bug: When using IPsec/IKEv2 with strongswan, you should create an iptables rule for forwarding/NATing the traffic like this ( https://www.digitalocean.com/community/tutorials/how-to-set-up-an-ikev2-vpn-server-with-strongswan-on-ubuntu-16-04#step-6-%E2%80%94-configuring-the-firewall-&-kernel-ip-forwarding )

`iptables -A FORWARD -s 10.8.6.0/24 -p esp -m policy --dir in --pol ipsec -j ACCEPT`

Creating this rule with the lib works just fine, but it cannot be deleted once inserted. Tried e.g. with this code (the indexes are correct ofc for FORWARD chain/rule above)
```
import iptc
filt = iptc.Table("filter")
filt.refresh()
filt.chains[1].delete_rule(filt.chains[1].rules[0])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/iptc/ip4tc.py", line 1489, in delete_rule
    self.table.delete_entry(self.name, rbuf, rule.mask)
  File "/usr/local/lib/python3.5/dist-packages/iptc/ip4tc.py", line 1519, in new
    ret = fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/iptc/ip4tc.py", line 1776, in delete_entry
    (chain, self.strerror()))
iptc.ip4tc.IPTCError: can't delete entry from chain FORWARD: b'Bad rule (does a matching rule exist in that chain?)'
```

**Comment by ldx** [comment]
Interesting, works for me here on master:

```>>> filt.refresh()
>>> rule = chain.rules[-1]
>>> rule.src
'10.8.6.0/255.255.255.0'
>>> filt.chains[1].delete_rule(filt.chains[1].rules[-1])```

**Comment by ldx** [comment]
Can you test this with python-iptables from current master?

**Comment by jllorente** [comment]
I can't reproduce the issue either.
@TearsDontFalls what version were you using?

**Comment by TearsDontFalls** [comment]
@ldx  @jllorente Thanks, was fixed meanwhile on master :)

Didnt work with 0c3c0cb.
