### ISSUE TITLE
Is it possible to set log prefixes with python-iptables?

### ISSUE THREAD

**Issue by TrustArgon** [ldx/python-iptables#262]
In an attempt to automate redundant work, I've turned to and had great success with python-iptables. The only issue I'm having is that I cannot seem to find a way to use python-iptables to duplicate a rule written as such:

iptables -A CUSTOM_CHAIN -j LOG --log-prefix "Desired log prefix: " --log-level 6

specifically, is it possible to use python-iptables to set the --log-prefix and --log-level parameters?

**Comment by ldx** [comment]
Sure, something like this should work:

    import iptc
    
    table = iptc.Table(iptc.Table.FILTER)
    table.refresh()
    default_chain = iptc.Chain(table, 'CUSTOM_CHAIN')
    rule = iptc.Rule()
    rule.protocol = 'tcp'
    rule.target = iptc.Target(rule, 'LOG')
    rule.target.log_prefix = "Desired log prefix:"
    rule.target.log_level = "6"
    default_chain.insert_rule(rule)
