### ISSUE TITLE
Valid rule without a target cannot be created

### ISSUE THREAD

**Issue by batkins61** [ldx/python-iptables#265]
I am trying to create a rule to just provide counters for IP addresses using version 0.13.0.  I can add the rule with the CLI as follows:
`iptables -A IP_ACCT -dst 10.10.10.10`

when I execute that command, iptables -S yields
`-A IP_ACCT -d 10.10.10.10/32`

and iptables -L -n -v yields:
```
Chain IP_ACCT (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0            all  --  *      *       0.0.0.0/0            10.10.10.10
```

However, when I attempt to create the rule as follows:
```
import iptc
chain = iptc.Chain(iptc.Table(iptc.Table.FILTER), "IP_ACCT")
rule = iptc.Rule()
rule.src = "10.10.10.10"
chain.insert_rule(rule)
```
I get:
```
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iptc
>>> chain = iptc.Chain(iptc.Table(iptc.Table.FILTER), "IP_ACCT")
>>> rule = iptc.Rule()
>>> rule.src = "10.10.10.10"
>>> chain.insert_rule(rule)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/iptc/ip4tc.py", line 1437, in insert_rule
    raise ValueError("invalid rule")
ValueError: invalid rule
```
If I add a target, it works.

**Comment by ldx** [comment]
I think the workaround is simply `rule.create_target("")` before inserting it.

**Comment by jllorente** [comment]
@batkins61 , I don't know if we want to change the behavior of the library for this particular bit, however this PR https://github.com/ldx/python-iptables/pull/273 adds support for undefined/missing and _goto_ targets when using dictionary rules.
```
import iptc
iptc.easy.insert_rule('filter', 'FORWARD', {'dst':'10.10.10.10'})
```

**Comment by jllorente** [comment]
The fix is now available in master when using dictionary rules, otherwise use `rule.create_target("")` as indicated above.
