### ISSUE TITLE
DNAT rule error tcp match: only valid for protocol 6 in dmesg

### ISSUE THREAD

**Issue by invano** [ldx/python-iptables#267]
Hi,
I'm trying this package for the first time. Maybe this is a no-issue and it's just me typing the rule from python incorrectly.

I'd like to create the following rule to route all the traffic from one interface to another except one port:
```
iptables -t nat -D PREROUTING -i $IFACE -s $SOURCE -p tcp ! --dport $PORT -j DNAT --to-destination $DEST
```

I translated the rule above in the following way:
```
rule = iptc.Rule()
chain = iptc.Chain(iptc.Table(iptc.Table.NAT), "PREROUTING")
target = rule.create_target("DNAT")
match = rule.create_match("tcp")
rule.in_interface = $IFACE
rule.src = $SOURCE
match.dport = "!"+$PORT
target.to_destination = $DEST

chain.insert_rule(rule)
```

From python this seems to work and I don't get any error/exception, but if I do `iptables -t nat -L` the rule doesn't appear. I also see in dmesg that the python code triggered `x_tables: ip_tables: tcp match: only valid for protocol 6`. Same error if I don't use `!`, the problem seems to be the match tcp part.
On the other hand, the rule inserted directly using iptables perfectly works.

I'm on an Ubuntu 18.04.2 LTS machine, using python3 and installed the package via pypy (pip3).

**Comment by ldx** [comment]
Try to also set the protocol for the rule, i.e.

    rule.protocol = "tcp"

**Comment by invano** [comment]
True that. I don't know why I was taking it for granted.
