### ISSUE TITLE
Chain counters show always zero values for packets and bytes

### ISSUE THREAD

**Issue by MaelStor** [ldx/python-iptables#280]
When trying to use `packet_counter, byte_counter = chain.get_counters()` where chain is a Chain object with a builtin chain (I've tried all in FILTER: INPUT, OUTPUT, FORWARD) the resulting tuple is always (0,0). Even refreshing the table as mentioned in #47 doesn't update the values. Output with `iptables -L -vn --line-num` shows non-zero values for the chains.

**Comment by jllorente** [comment]
I tried with the function from the iptc.easy module and it works, since it always fetches the a refreshed view of the iptc table/chain/rule object.

```
In [5]: iptc.easy.insert_rule('filter', 'OUTPUT', {'dst':'10.10.10.10'})

In [6]: iptc.easy.get_rule_counters('filter', 'OUTPUT', {'dst':'10.10.10.10'})
Out[6]: (0, 0)

>>> $ ping 10.10.10.10 -c 2

In [7]: iptc.easy.get_rule_counters('filter', 'OUTPUT', {'dst':'10.10.10.10'})
Out[7]: (2, 168)
```

**Comment by MaelStor** [comment]
Sorry my mistake I've checked the wrong table for non-zero chain counters. I've tried it again and it's working with chain.get_counters() and your method for rules.
