### ISSUE TITLE
install python-iptables error

### ISSUE THREAD

**Issue by wrwahut** [ldx/python-iptables#281]
ERROR: Complete output from command /usr/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-Ll45yc/python-iptables/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_3xAFc/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/iptc
    copying iptc/util.py -> build/lib.linux-x86_64-2.7/iptc
    copying iptc/__init__.py -> build/lib.linux-x86_64-2.7/iptc
    copying iptc/ip6tc.py -> build/lib.linux-x86_64-2.7/iptc
    copying iptc/easy.py -> build/lib.linux-x86_64-2.7/iptc
    copying iptc/ip4tc.py -> build/lib.linux-x86_64-2.7/iptc
    copying iptc/version.py -> build/lib.linux-x86_64-2.7/iptc
    copying iptc/errors.py -> build/lib.linux-x86_64-2.7/iptc
    copying iptc/xtables.py -> build/lib.linux-x86_64-2.7/iptc
    running build_ext
    building 'libxtwrapper' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/libxtwrapper
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c libxtwrapper/wrapper.c -o build/temp.linux-x86_64-2.7/libxtwrapper/wrapper.o
    gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/libxtwrapper/wrapper.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/libxtwrapper.so
    /usr/bin/ld: cannot find -lpython2.7
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-Ll45yc/python-iptables/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_3xAFc/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-Ll45yc/python-iptables/

**Comment by ldx** [comment]
You need to install the C includes/headers for Python. Likely the package is either called python-dev or python-devel in your Linux distribution.

**Comment by wrwahut** [comment]
my os is centos, I have installed python-devel  by "yum install python-devel", but install error exist .
libiptc.so, libxtables.so in /usr/lib64

**Comment by wrwahut** [comment]
firstly，thanks very!! the issue is solved
