### ISSUE TITLE
iptables handler stays open

### ISSUE THREAD

**Issue by hheennrryy21** [ldx/python-iptables#284]
I have software which continuously runs and updates iptables using **iptc**.

The issue I found was that I see open raw sockets after adding the rules. 

After a long time I can easily have more than 20 open raw sockets. 

To replicate the issue run the following:

**Code snippet**
```
import iptc
import time


if __name__=="__main__":
    rule = iptc.Rule()
    table_filter = iptc.Table(iptc.Table.FILTER)
    input_chain = iptc.Chain(table_filter, "INPUT")
    rule.target = iptc.Target(rule, "ACCEPT")
    time.sleep(100) # sleep so we can have time to see the netstat output
```
**Then run this on Linux**
`watch netstat -wvpa`

Observe the raw sockets. They remain open. 

There is a way to close the iptc.Table() object using a close() method, and that closes the raw socket. But there isn't one for the iptc.Target object.

**Where Problem Occurs**

_get_tables function in Rule() class of ip4tc.py

Calls Table(t) on every table and causes objects of Table to instantiated. Since the object is created without being referenced, there is no way to shut down the iptables handler later.

**Version**
python-iptables (0.13.0)

**Comment by ldx** [comment]
Tables should be singletons, but there is a chance we're leaking them somewhere.

Can you reproduce the leak (and is it a real leak, i.e. more and more sockets get opened over time without ever reaching a reasonable max number) via creating rules or calling the offending function repeatedly?

**Comment by hheennrryy21** [comment]
ldx, you are right. I found out in my software what that the issue was something else.

python-iptables indeed only has a Table singleton. I could not replicate the multiple rule insertion. I found out some other piece of code was doing. Next time I'll be sure to triple check before opening an issue.

Thanks again!

**Comment by ldx** [comment]
Cool, thanks for getting back to me!
