### ISSUE TITLE
Do we have a way to set chai/rule counter to some offset when inserting or appending rules ?

### ISSUE THREAD

**Issue by dolenam317** [ldx/python-iptables#288]
Do we have some way to set the rule counters when inserting or appending a rule ? I tried 

`
$rule_d = {'src': '172.168.168.129/32', 'in-interface': 'br0', 'mac': {'mac-source': '11:22:33:44:55:66'}, 'target': 'test_counters', 'counters': [0, 12345]}
$iptc_easy.insert_rule('mangle', 'FORWARD', rule_d)
`

Verify again using 
`iptables -t mangle -nxvL FORWARD`

Result:

> Chain FORWARD (policy ACCEPT 9 packets, 1592 bytes)
>     pkts      bytes target     prot opt in     out     source               destination         
>        0        0 test_counter  all  --  br0    *       172.168.168.129      0.0.0.0/0            MAC 11:22:33:44:55:66

Expected result:

> Chain FORWARD (policy ACCEPT 9 packets, 1592 bytes)
>     pkts      bytes target     prot opt in     out     source               destination         
>        0        12345 test_counter  all  --  br0    *       172.168.168.129      0.0.0.0/0            MAC 11:22:33:44:55:66

**Comment by ldx** [comment]
Does this work from the command line?

**Comment by jllorente** [comment]
Currently there is only support for getting the counters in (numberOfBytes, numberOfPackets) format via iptc.easy.get_rule_counters()

I can look into how to add more support for rule counters :)

**Comment by jllorente** [comment]
Hei @dolenam317  and @ldx! Can you take a look at PR https://github.com/ldx/python-iptables/pull/289 ?
I have added some extra support for counters :)

**Comment by jllorente** [comment]
This is how I tested it:

```
import iptc
rule_d = {'protocol': 'icmp', 'dst':'8.8.8.8', 'counters':(100,100)}
iptc.easy.insert_rule('filter', 'OUTPUT', rule_d)
iptc.easy.dump_chain('filter', 'OUTPUT')
>> [{'counters': (100, 100), 'dst': '8.8.8.8/32', 'protocol': 'icmp'}]

## Send 2 ICMP probes to Google to increase counters
## ping 8.8.8.8 -c 2

iptc.easy.dump_chain('filter', 'OUTPUT')
>>[{'counters': (102, 268), 'dst': '8.8.8.8/32', 'protocol': 'icmp'}] 

## Reset counters back to (100,100) via rule replacement
## Note: Counters are not used to match a rule, so we can use the same rule_d definition
iptc.easy.replace_rule('filter', 'OUTPUT', rule_d, rule_d)

iptc.easy.dump_chain('filter', 'OUTPUT')
>>[{'counters': (100, 100), 'dst': '8.8.8.8/32', 'protocol': 'icmp'}] 
```

**Comment by dolenam317** [comment]
@jllorente Thank you, this is exactly what I am looking for.
