### ISSUE TITLE
cannot get options for iptable match extensions

### ISSUE THREAD

**Issue by christian-2** [ldx/python-iptables#294]
I am getting started with `python-iptables` (v0.14.0 with Python 3.7.3) and run a program that loops over tables, chains, and then prints all rules including matches. For a match with `match.name == 'tcp'` I would have expected that there is an instance attribute `match.dport`, because the documentation [1] says "parameters are implemented as instance attributes in python" and `man iptables-extensions` specifies `--destination-port,--dport port[:port]` for `tcp`. However, `match.__dict__['dport']` raises a `KeyError`, i.e. the instance attribute (apparently) does not exist.

So what it a right way to get at such parameters (options) for iptables match (and target) extensions. (The documentation mainly covers creating such entities, not retrieving them.)
 
[1] http://ldx.github.io/python-iptables/usage.html#rule

**Comment by ldx** [comment]
Don't use `__dict__` directly, use `match.dport`.

**Comment by christian-2** [comment]
> Don't use `__dict__` directly, use `match.dport`.

Yes, I can do that. But I was hoping that there was a way of looping over all such entities (for printing purposes) without knowing their exact names up front.

**Comment by ldx** [comment]
You can try `print match.get_all_parameters()` if you're curious about all the key/value parameters of a match or target.

**Comment by christian-2** [comment]
That nails it, thx.
