### ISSUE TITLE
Support for nftables

### ISSUE THREAD

**Issue by vhaidamaka** [ldx/python-iptables#298]
Hi,

python-iptables library uses iptables-legacy, but currently a number of distributions (Debian, Fedora, CentOS etc) switched to nftables. Some distros ships iptables-legacy binary for smooth migration, but for example, CentOS doesn't and it makes this library unusable.

Do you have any plans to support nftables?
Thanks.

Related issue https://github.com/ldx/python-iptables/issues/297

**Comment by ldx** [comment]
I haven't looked into how much work it would be. It might be better to start a new greenfield project for nftables, I expect that lots of things have changed between iptables and nftables (even though they provide a compatibility layer).
