### ISSUE TITLE
Matching with dscp values

### ISSUE THREAD

**Issue by nandujayakumar** [ldx/python-iptables#313]
Don't we have any provision to match using DSCP value ????  Was not able to find the appropriate  python API for it

**Comment by ldx** [comment]
Example:

    import iptc
    
    table = iptc.Table("filter")
    chain = iptc.Chain(table, "INPUT")
    rule = iptc.Rule(chain=chain)
    rule.protocol = "tcp"
    match = rule.create_match("dscp")
    match.dscp_class = "BE"
    target = rule.create_target("ACCEPT")
    chain.insert_rule(rule)

**Comment by nandujayakumar** [comment]
Thanks @ldx
