### ISSUE TITLE
Can I use python-iptables on Python 3.6?

### ISSUE THREAD

**Issue by shadychan** [ldx/python-iptables#331]
In README.md, it says `Python-iptables supports Python 2.6, 2.7 and 3.4`

Can I use python-iptables on Python 3.6?

**Comment by ldx** [comment]
> In README.md, it says `Python-iptables supports Python 2.6, 2.7 and 3.4`
> 
> Can I use python-iptables on Python 3.6?

Yup, Python >= 3.4 should be fine.
