### ISSUE TITLE
"Can't find directory with extensions; please set XTABLES_LIBDIR"

### ISSUE THREAD

**Issue by peakwinter** [ldx/python-iptables#37]
Hi there!

I have run into an issue with iptables 1.4.19.1-1 on Arch Linux, with Python2.7.5, using the version of this plugin available via Git. This error is being returned just after install, and I can't do anything with the plugin. I tried Googling what this variable should be set to but I cannot seem to find any information anywhere. While using the version of the plugin available via PIP, I got the same error as #28, so I tried to upgrade to the Git version and that's what happened.

If you have any hints, I would love to hear them :) Here is the full stacktrace.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/iptc/__init__.py", line 10, in <module>
    from ip4tc import (is_table_available, Table, Chain, Rule, Match, Target,
  File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 12, in <module>
    from xtables import (XT_INV_PROTO, NFPROTO_IPV4, XTablesError, xtables,
  File "/usr/lib/python2.7/site-packages/iptc/xtables.py", line 692, in <module>
    raise XTablesError("can't find directory with extensions; "
iptc.xtables.XTablesError: can't find directory with extensions; please set XTABLES_LIBDIR
```

Thank you!

**Comment by alx-k** [comment]
I'm running into the same issue on Ubuntu 17.04 (or 16.04) with Python 3.6 - I can't seem to fix it.

I didn't have `libxtables.so` but have `libxtables.so.11` in `/usr/lib/x86_64-linux-gnu/`, so I created a symbolic link and set `export XTABLES_LIBDIR=/usr/lib/x86_64-linux-gnu` and did the same for `libiptc.so`. I'm still getting the same issue.

Are there any clues on how I can get it working? For the record it worked fine on 16.04 with Python 3.5 but I had a need for some 3.6 features.

**Comment by ldx** [comment]
@alx-k try `XTABLES_LIBDIR=/usr/lib/x86_64-linux-gnu/xtables/` after making sure `iptables` is installed.

**Comment by alx-k** [comment]
@ldx I gave that a try (also check `iptables`, is installed by default on Ubuntu server as well). I'm still getting the same issue.

**Comment by ldx** [comment]
@alx-k interesting, this worked for me on Ubuntu 17.04 + Python 3.6.

Can you check if you have an `/usr/lib/x86_64-linux-gnu/xtables/` directory, and if you do, what's inside?

**Comment by amy61789** [comment]
I installed Ubuntu 16.10 on a VirtualBox. I'm trying to import iptc from iptables and continue to receive the same error of "can't find directory with extensions; please set XTABLES_LIBDIR". I've changed the XTABLE_LIBDIR environment variable, no change.

**Comment by ldx** [comment]
@amy61789 what do you use for XTAB:ES_LIBDIR?

**Comment by amy61789** [comment]
Here is the actual repo that I'm working on: https://github.com/amy61789/captive_portal/tree/master/captive_portal/captive_portal

I'm trying to create a Captive Portal to authenticate users/time out. When the script hits the iptablesHandler.py it tries to import iptc. As soon as the code meets that line I get the error. I'm assuming that I may need the XTABLES_LIBDIR to import iptc?

**Comment by ldx** [comment]
@amy61789 can you try `export XTABLES_LIBDIR=/lib/xtables`?

**Comment by amy61789** [comment]
@ldx still receiving the same error after try the export XTABLES_LIBDIR=/lib/xtables.

Error message is as follows:
<img width="816" alt="screen shot 2017-08-10 at 11 44 27 am" src="https://user-images.githubusercontent.com/20174873/29186434-57b56f42-7dc1-11e7-915d-f01ebdee2302.png">

**Comment by ldx** [comment]
@amy61789 two things we can check:
- `ls /lib/xtables`
- Do you use `sudo` to run your app or script?

**Comment by amy61789** [comment]
@ldx 
Yes, I use sudo to run the script. After entering ls /lib/xtables in the terminal, it returns the message "ls: cannot access '/lib/xtables': No such file or directory"

**Comment by ldx** [comment]
Can you check what `dpkg -L iptables` says on that box?

**Comment by amy61789** [comment]
The output is:

(.env) amy@amy-VirtualBox:~$ dpkg -L iptables
/.
/sbin
/sbin/xtables-multi
/usr
/usr/bin
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/xtables
/usr/lib/x86_64-linux-gnu/xtables/libip6t_DNAT.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_DNPT.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_HL.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_LOG.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_MASQUERADE.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_NETMAP.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_REDIRECT.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_REJECT.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_SNAT.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_SNPT.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_ah.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_dst.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_eui64.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_frag.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_hbh.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_hl.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_icmp6.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_ipv6header.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_mh.so
/usr/lib/x86_64-linux-gnu/xtables/libip6t_rt.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_CLUSTERIP.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_DNAT.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_ECN.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_LOG.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_MASQUERADE.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_NETMAP.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_REDIRECT.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_REJECT.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_SNAT.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_TTL.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_ULOG.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_ah.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_icmp.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_realm.so
/usr/lib/x86_64-linux-gnu/xtables/libipt_ttl.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_AUDIT.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_CHECKSUM.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_CLASSIFY.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_CONNMARK.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_CONNSECMARK.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_CT.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_DSCP.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_HMARK.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_IDLETIMER.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_LED.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_MARK.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_NFLOG.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_NFQUEUE.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_NOTRACK.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_RATEEST.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_SECMARK.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_SET.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_SYNPROXY.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_TCPMSS.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_TCPOPTSTRIP.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_TEE.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_TOS.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_TPROXY.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_TRACE.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_addrtype.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_bpf.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_cgroup.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_cluster.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_comment.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_connbytes.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_connlabel.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_connlimit.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_connmark.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_conntrack.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_cpu.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_dccp.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_devgroup.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_dscp.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_ecn.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_esp.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_hashlimit.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_helper.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_ipcomp.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_iprange.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_ipvs.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_length.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_limit.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_mac.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_mangle.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_mark.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_multiport.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_nfacct.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_osf.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_owner.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_physdev.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_pkttype.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_policy.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_quota.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_rateest.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_recent.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_rpfilter.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_sctp.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_set.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_socket.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_standard.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_state.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_statistic.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_string.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_tcp.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_tcpmss.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_time.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_tos.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_u32.so
/usr/lib/x86_64-linux-gnu/xtables/libxt_udp.so
/usr/sbin
/usr/sbin/iptables-apply
/usr/sbin/nfnl_osf
/usr/share
/usr/share/doc
/usr/share/doc/iptables
/usr/share/doc/iptables/INCOMPATIBILITIES
/usr/share/doc/iptables/README.Debian
/usr/share/doc/iptables/copyright
/usr/share/doc/iptables/html
/usr/share/doc/iptables/html/NAT-HOWTO-1.html
/usr/share/doc/iptables/html/NAT-HOWTO-10.html
/usr/share/doc/iptables/html/NAT-HOWTO-11.html
/usr/share/doc/iptables/html/NAT-HOWTO-2.html
/usr/share/doc/iptables/html/NAT-HOWTO-3.html
/usr/share/doc/iptables/html/NAT-HOWTO-4.html
/usr/share/doc/iptables/html/NAT-HOWTO-5.html
/usr/share/doc/iptables/html/NAT-HOWTO-6.html
/usr/share/doc/iptables/html/NAT-HOWTO-7.html
/usr/share/doc/iptables/html/NAT-HOWTO-8.html
/usr/share/doc/iptables/html/NAT-HOWTO-9.html
/usr/share/doc/iptables/html/NAT-HOWTO.html
/usr/share/doc/iptables/html/packet-filtering-HOWTO-1.html
/usr/share/doc/iptables/html/packet-filtering-HOWTO-10.html
/usr/share/doc/iptables/html/packet-filtering-HOWTO-11.html
/usr/share/doc/iptables/html/packet-filtering-HOWTO-2.html
/usr/share/doc/iptables/html/packet-filtering-HOWTO-3.html
/usr/share/doc/iptables/html/packet-filtering-HOWTO-4.html
/usr/share/doc/iptables/html/packet-filtering-HOWTO-5.html
/usr/share/doc/iptables/html/packet-filtering-HOWTO-6.html
/usr/share/doc/iptables/html/packet-filtering-HOWTO-7.html
/usr/share/doc/iptables/html/packet-filtering-HOWTO-8.html
/usr/share/doc/iptables/html/packet-filtering-HOWTO-9.html
/usr/share/doc/iptables/html/packet-filtering-HOWTO.html
/usr/share/doc-base
/usr/share/doc-base/nat
/usr/share/doc-base/packet-filter
/usr/share/iptables
/usr/share/iptables/iptables.xslt
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/iptables
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/iptables-xml.1.gz
/usr/share/man/man8
/usr/share/man/man8/iptables-apply.8.gz
/usr/share/man/man8/iptables-extensions.8.gz
/usr/share/man/man8/iptables-restore.8.gz
/usr/share/man/man8/iptables-save.8.gz
/usr/share/man/man8/iptables.8.gz
/usr/share/man/man8/nfnl_osf.8.gz
/usr/share/man/man8/xtables-multi.8.gz
/sbin/ip6tables
/sbin/ip6tables-restore
/sbin/ip6tables-save
/sbin/iptables
/sbin/iptables-restore
/sbin/iptables-save
/usr/bin/iptables-xml
/usr/sbin/ip6tables-apply
/usr/share/doc/iptables/changelog.Debian.gz
/usr/share/man/man8/ip6tables-apply.8.gz
/usr/share/man/man8/ip6tables-restore.8.gz
/usr/share/man/man8/ip6tables-save.8.gz
/usr/share/man/man8/ip6tables.8.gz

**Comment by ldx** [comment]
@amy61789 okay, then `export XTABLES_LIBDIR=/usr/lib/x86_64-linux-gnu/xtables/` should work. Probably when you use sudo to run your app, that resets the environment variables.

**Comment by amy61789** [comment]
@ldx Awesome that works, thanks! I'll throw it in my bashrc file so I don't need to export every time.

**Comment by A-new-b** [comment]
> This is the directory in which the extensions are (lots of shared libraries, `libipt_*.so`, `libip6t_*.so` and `libxt_*.so`). On my Debian system, this is `/lib/xtables`. It seems on Arch this is `/usr/lib/iptables`: https://www.archlinux.org/packages/core/x86_64/iptables/
> 
> So setting `XTABLES_LIBDIR` to `/usr/lib/iptables` should do the trick.

now,`XTABLES_LIBDIR` should be set to `usr/lib/xtables` in archlinux,
I spend almost two hours in it
