### ISSUE TITLE
Unable de find /proc/sys/kernel/modprobe

### ISSUE THREAD

**Issue by hegusung** [ldx/python-iptables#65]
Hello, I've got some issues when I'm importing iptc
Here is the output:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/iptc/**init**.py", line 10, in <module>
    from ip4tc import (is_table_available, Table, Chain, Rule, Match, Target,
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 18, in <module>
    load_kernel("ip_tables")
  File "/usr/local/lib/python2.7/dist-packages/iptc/util.py", line 24, in load_kernel
    rc, err = _load_ko(name)
  File "/usr/local/lib/python2.7/dist-packages/iptc/util.py", line 15, in _load_ko
    proc = open("/proc/sys/kernel/modprobe")
IOError: [Errno 2] No such file or directory: '/proc/sys/kernel/modprobe'

My system is the latest Debian and /proc/sys/kernel/modprobe does not exists in my system, but /sbin/modprobe exists. 

What should I do ?

**Comment by skrzyp** [comment]
I have the same issue.
That error is thrown when I'm using custom kernel with bulit-in netfilter on Gentoo, so you need to provide other method for checking netfilter/iptables existence on running system.
IPython backtrace:
```
In [5]: import iptc
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-5-49a367781e85> in <module>()
----> 1 import iptc

/usr/lib64/python2.7/site-packages/iptc/__init__.py in <module>()
      8 """
      9 
---> 10 from iptc.ip4tc import (is_table_available, Table, Chain, Rule, Match, Target,
     11                    Policy, IPTCError)
     12 from iptc.ip6tc import is_table6_available, Table6, Rule6

/usr/lib64/python2.7/site-packages/iptc/ip4tc.py in <module>()
     16 __all__ = ["Table", "Chain", "Rule", "Match", "Target", "Policy", "IPTCError"]
     17 
---> 18 load_kernel("ip_tables")
     19 
     20 _IFNAMSIZ = 16

/usr/lib64/python2.7/site-packages/iptc/util.pyc in load_kernel(name, exc_if_failed)
     30 # Load a kernel module. If it is already loaded modprobe will just return 0.
     31 def load_kernel(name, exc_if_failed=False):
---> 32     rc, err = _load_ko(name)
     33     if rc:
     34         if not err:

/usr/lib64/python2.7/site-packages/iptc/util.pyc in _load_ko(modname)
     21 def _load_ko(modname):
     22     # this will return the full path for the modprobe binary
---> 23     proc = open("/proc/sys/kernel/modprobe")
     24     modprobe = proc.read(1024)
     25     if modprobe[-1] == '\n':

IOError: [Errno 2] No such file or directory: '/proc/sys/kernel/modprobe'

```

**Comment by ldx** [comment]
@skrzyp I pushed a fix, can you confirm that this resolves your problem?
